### ISSUE TITLE
Ошибка Incorrect AppMetrica Version

### ISSUE THREAD

**Issue by maramak** [yandexmobile/yandex-ads-unity-plugin#104]
Здравствуйте!

Сегодня решил обновить версию AppMetrica до последней. После чего собрал проект и запустил на Android устройстве, и в логкате получил ошибки:

```
2024.07.12 19:48:43.913 13328 13328 Error YandexAds [Integration] Found following errors for banner ad type: 
2024.07.12 19:48:43.913 13328 13328 Error YandexAds  - Incorrect AppMetrica Version. The minimum supported version of AppMetrica SDK is 6.0.0 (inclusive) and the maximum supported version is 7.0.0 (exclusive). And the current version of AppMetrica SDK is 7.0.0
```

Плюс аналогичные ошибки для интерстишиалов и ревардов.

Вы можете это исправить? Или же не надо откатить версию AppMetrica или  Yandex Mediation?

Unity 2022.3.37f1, AppMetrica 6.2.0,  yandex-mobileads-mediation-7.1.0

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-3454. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-3454 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by mobile-ads-github** [comment]
Здравствуйте! На данный момент мы не поддерживаем AppMetrica SDK версии 7 и выше. Вам нужно использовать более младшую версию
