### ISSUE TITLE
Переименовать некоторые события и событие инициализации sdk

### ISSUE THREAD

**Issue by RocksteadyDog** [yandexmobile/yandex-ads-unity-plugin#108]
Здравствуйте! Небольшое предложение на рассмотрение, переименовать события OnAdShown в OnAdStart или в OnAdOpened, а OnAdDismissed в OnAdClosed или в OnAdCompleted, новые названия лучше отразят суть, чем Shown и Dismissed.
И добавьте событие инициализации sdk  ->  MobileAds.onSdkInitializationCompletedEvent += OnInitializationComplete; или  MobileAds.InitializationCompleted(delegate{ // });
Заранее спасибо!

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-3574. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-3574 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by mobile-ads-github** [comment]
Добрый день! Мы рассмотрели ваше предложение. На данный момент не планируется переименование событий, т.к мы стараемся унифицировать названия на всех платформах.
