### ISSUE TITLE
A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable

### ISSUE THREAD

**Issue by Po4ti** [yandexmobile/yandex-ads-unity-plugin#110]
При разрешении зависимостей через Android Resolver во время сборки возникает множество ошибок дублирования классов

![image](https://github.com/user-attachments/assets/d44ffa1a-7938-4d2d-92c8-c9a7340d7508)

Unity: 2022.3.40f1
Plugin: 7.2.0

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-3622. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-3622 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by danopotap** [comment]
Столкнулся недавно с такой же проблемой, как решили?

**Comment by Po4ti** [comment]
Проверьте, что в assets/plugins/android нет файлов aar и jar конфликтующих либ (скорее всего, androidx). Если есть - попробуйте удалить.
