### ISSUE TITLE
CocoaPods Error

### ISSUE THREAD

**Issue by MaksimUstimenko** [yandexmobile/yandex-ads-unity-plugin#111]
Ошибка при попытке запуска проекта
YandexMobileAds version: 7.3.2
YandexMobileAdsMediation version: 7.3.2
Pod version: 1.15.2
MacOS: 13.6.3
Xcode: 15.1

> ld: Undefined symbols:
  __swift_FORCE_LOAD_$_swiftXPC, referenced from:
      __swift_FORCE_LOAD_$_swiftXPC_$_AppLovinYandexMobileAdsAdapters in AppLovinYandexMobileAdsAdapters[3] (YMAAppLovinMaxMediatedBannerAdapter.o)
      __swift_FORCE_LOAD_$_swiftXPC_$_AppLovinMobileAdsCoreAdapters in AppLovinYandexMobileAdsAdapters[11] (AppLovinAdapterInfoProvider.o)
      __swift_FORCE_LOAD_$_swiftXPC_$_BigoADSYandexMobileAdsAdapters in BigoADSYandexMobileAdsAdapters[3] (YMABigoADSMediatedBannerAdapter.o)
      __swift_FORCE_LOAD_$_swiftXPC_$_BigoADSMobileAdsCoreAdapters in BigoADSYandexMobileAdsAdapters[9] (BigoADSBidderTokenLoader.o)
      __swift_FORCE_LOAD_$_swiftXPC_$_ChartboostYandexMobileAdsAdapters in ChartboostYandexMobileAdsAdapters[3] (YMAChartboostMediatedBannerAdapter.o)
      __swift_FORCE_LOAD_$_swiftXPC_$_ChartboostMobileAdsCoreAdapters in ChartboostYandexMobileAdsAdapters[8] (ChartboostBannerSizeResolver.o)
      __swift_FORCE_LOAD_$_swiftXPC_$_GoogleYandexMobileAdsAdapters in GoogleYandexMobileAdsAdapters[3] (YMAAdMobMediatedBannerAdapter.o)
      ...
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-3631. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-3631 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by mobile-ads-github** [comment]
Добрый день,  нужно использовать Xcode версии 15.4

**Comment by MaksimUstimenko** [comment]
> Добрый день, нужно использовать Xcode версии 15.4

Спасибо за ответ, проблема ушла!
