### ISSUE TITLE
Юнити краш интерстишиала - com.yandex.mobile.ads.impl.sq1$b.$r8$lambda$VHAxEz6ZhjO5pQAuOxDs9DOgf7A

### ISSUE THREAD

**Issue by KolesovD** [yandexmobile/yandex-ads-unity-plugin#112]
При воспроизведении интерстишиала, когда показывается реклама самого Яндекса, иногда приложение крашится в случайный момент видео с фатальной ошибкой.
Версия SDK - 7.2.0
Версия Юнити - 2022.3.19f1

![photo_2024-08-15_19-46-26](https://github.com/user-attachments/assets/d3573594-0ac2-434c-867e-13774b67693b)

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-3632. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-3632 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by KolesovD** [comment]
А вот точно что поймал этот вылет на рекламе с наградой, которая лентой была.
![photo_2024-08-16_15-49-16](https://github.com/user-attachments/assets/e791db91-2d93-46a7-a284-ce99a6dfa48b)

**Comment by vesnagames** [comment]
В 7.3.0 проблема остается

**Comment by AntKarlov** [comment]
Присоединяюсь, обнаружил такую же проблему в отчетах Google Console. Версия SDK 7.3.0.

**Comment by SICREATOR** [comment]
Мне кажется дело в версии Unity, сам пока не проверил, но думаю дело в этом.

**Comment by AntKarlov** [comment]
> Мне кажется дело в версии Unity, сам пока не проверил, но думаю дело в этом.

Нет. На той же версии Unity откатился до предыдущей Yandex Ads SDK 7.0.1 (которая у меня была) — проблема сразу ушла, судя по аналитике.

**Comment by SICREATOR** [comment]
> > Мне кажется дело в версии Unity, сам пока не проверил, но думаю дело в этом.
> 
> Нет. На той же версии Unity откатился до предыдущей Yandex Ads SDK 7.0.1 (которая у меня была) — проблема сразу ушла, судя по аналитике.

Да это я понимаю, я говорил про версию  7.3.0, что она уже работает в Unity 6, потому что у меня такая же проблема, и таже самая версия Unity что у вас и [KolesovD](https://github.com/KolesovD), просто не охота проект перекатывать на 6 unity, и интересно есть ли данная проблема в ней.

**Comment by vesnagames** [comment]
Коллеги, напишите пожалуйста, в 7.4.0 ушла проблема?

**Comment by AntKarlov** [comment]
> > > Мне кажется дело в версии Unity, сам пока не проверил, но думаю дело в этом.
> > 
> > 
> > Нет. На той же версии Unity откатился до предыдущей Yandex Ads SDK 7.0.1 (которая у меня была) — проблема сразу ушла, судя по аналитике.
> 
> Да это я понимаю, я говорил про версию 7.3.0, что она уже работает в Unity 6, потому что у меня такая же проблема, и таже самая версия Unity что у вас и [KolesovD](https://github.com/KolesovD), просто не охота проект перекатывать на 6 unity, и интересно есть ли данная проблема в ней.

Скорее всего проблема от версии Unity не зависит, так как стектрейс указывает на ошибку в нативном коде рекламной библиотеки. Если у вас проект в продакшене, то я не советую мигрировать на Unity 6 так как она находится в превью.

**Comment by gashukov** [comment]
> Коллеги, напишите пожалуйста, в 7.4.0 ушла проблема?

Используем AppLovin с адаптером Yandex. Адаптер на 7.4.0 версию. Проблема не такая же, но похожая. У 10% пользователей краши.

`Exception java.lang.Error: FATAL EXCEPTION [YandexAds.BaseController]

Unity version : 2022.3.31f1

Caused by: java.lang.NoSuchMethodError: No static method registerReceiver(Landroid/content/Context;Landroid/content/BroadcastReceiver;Landroid/content/IntentFilter;I)Landroid/content/Intent; in class Landroidx/core/content/ContextCompat; or its super classes (declaration of 'androidx.core.content.ContextCompat' appears in base.apk!classes7.dex)
at com.yandex.mobile.ads.impl.s81.a (SourceFile:43)
at com.yandex.mobile.ads.impl.s81.$r8$lambda$x5mVxp47CLvC6Yy_vwbSt1M6fWw
at com.yandex.mobile.ads.impl.s81$$ExternalSyntheticLambda0.run
at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
at java.lang.Thread.run (Thread.java:920)`

**Comment by KolesovD** [comment]
> Caused by: java.lang.NoSuchMethodError: No static method

Вполне вероятно, что на тот же самый статический метод ругается.

**Comment by mobile-ads-github** [comment]
Добрый день! Мы продолжаем работать над решением этой проблемы

**Comment by louken** [comment]
Та же проблема, как у коллег выше.
Замечено, что краш происходит на Rewarded и Interstitial рекламах, в которых есть аудио. В момент воспроизведения рекламы достаточно изменить системную громкость аудио на телефоне клавишами громкости, сразу происходит краш. Если в рекламе нет аудио, то и краша не наблюдается. Воспроизводится стабильно, хотя рекламу с аудио получить не просто.

Unity 2022.3.30f1, IL2CPP
yandex-mobileads-lite-7.3.0
appmetrica-unity-plugin v6.1.0
Замечено на устройствах Xiaomi и Redmi, Android 11+, например, Xiaomi 12T Pro, Redmi Note 10 Pro и Redmi Note 8 Pro. Но наша статистика пока слишком мелкая, чтобы судить наверняка.

```
java.lang.NoSuchMethodError: No static method -$$Nest$md(Lcom/yandex/mobile/ads/impl/wr1;)V in class Lcom/yandex/mobile/ads/impl/wr1; or its super classes (declaration of 'com.yandex.mobile.ads.impl.wr1' appears in base.apk!classes2.dex)
	at com.yandex.mobile.ads.impl.wr1$b.$r8$lambda$B-fNWrxWq_9ULcVBezH_aHeH2Qg(Unknown Source)
	at com.yandex.mobile.ads.impl.wr1$b$$ExternalSyntheticLambda0.run(Unknown Source)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8296)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
```

![Screenshot_2024-10-09-12-04-50-720_com paradoxonic onlyfruit_1](https://github.com/user-attachments/assets/ce8a8bfe-414b-4726-8928-c0855297d142)

![Screenshot_2024-10-09-12-12-35-636_com paradoxonic onlyfruit_1](https://github.com/user-attachments/assets/d1b13828-d160-4b87-b5c8-7be36ccfcc81)

**Comment by vesnagames** [comment]
у нас на 7.5.0 проблема ушла, протестировали на одном приложении

**Comment by KolesovD** [comment]
Тоже установил 7.5.0. Данной проблемы больше не наблюдаю.
