### ISSUE TITLE
Xcode Undefined symbols OBJC_CLASS_$_UnityAds 

### ISSUE THREAD

**Issue by dragoff** [yandexmobile/yandex-ads-unity-plugin#114]
Unity project build error Xcode:
```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_UnityAds", referenced from:
       in UnityAdsYandexMobileAdsAdapters[23](UnityAdsWrapperImpl.o)
```

Единая сборка медиаций и плагин 7.3.0 или 7.2.0.
Android собирается нормально.

<img width="475" alt="image" src="https://github.com/user-attachments/assets/88097922-f5d1-4d90-bd47-5cc05163ca0d">

<img width="412" alt="image" src="https://github.com/user-attachments/assets/a92a9175-4f98-4fc5-ab5a-7de730344825">

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-3655. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-3655 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by mobile-ads-github** [comment]
Добрый день, попробуйте обновиться до 7.4.0. 
Если нужна версия ниже 7.4.0, попробуйте добавить `pod 'UnityAds', '= 4.12.1'` в Podfile проекта.

**Comment by dragoff** [comment]
7.4.0 для Unity только что опубликовали. Работает. Спасибо.

**Comment by dragoff** [comment]
7.4.0 для Unity только что опубликовали. Работает. Спасибо.

**Comment by vfilho** [comment]
The problem is back on version 7.6.0

**Comment by mobile-ads-github** [comment]
Hello, @vfilho! We don't see a problem with Unity Ads for version 7.6.0. You can try to delete ~/.cocoapods folder and retry pod install in your project.
