### ISSUE TITLE
Переделайте шаблон ответа😀

### ISSUE THREAD

**Issue by RocksteadyDog** [yandexmobile/yandex-ads-unity-plugin#115]
Здравствуйте! 
Предложение, переделайте пожалуйста ваш шаблон ответа - "Спасибо за Ваше обращение, для разбора создана задача с номером {0} Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number {0} has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.".

Конкретно фразу "вернемся с ответом в течение 2 дней", на "вернемся с ответом как можно скорее" или подобное, потому что вы не возвращаетесь с ответом в течении 2 дней в большинстве случаев, новая запись будет отражать реальность более достоверно.
Заранее спасибо! SDK супер 👍

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-3686. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-3686 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by mobile-ads-github** [comment]
Добрый день! Мы поменяли автоматическое сообщение на предложенный вами вариант. Спасибо за проявленную инициативу!
