### ISSUE TITLE
Невозможно использовать плагин без iOS Build Support

### ISSUE THREAD

**Issue by aleverdes** [yandexmobile/yandex-ads-unity-plugin#12]
В директиву `#if UNITY_IOS` не обернут файл PostprocessBuildPlayerYandexMobileAds. Из-за этого компилятор ругается на строчку 12 (`using UnityEditor.iOS.Xcode;`) и на использование `PBXProject`.

Соответственно, если у меня приложение только под Android, мне всё равно в Unity потребуется установить iOS Build Support.

```
Assets/YandexMobileAds/Editor/PostprocessBuildPlayerYandexMobileAds.cs:12
```

**Comment by mobile-ads-github** [comment]
Здраствуйте! Передадим команде разработки.

**Comment by dreamcodestudio** [comment]
Аналогичная ситуация, желательно обертнуть целиком класс в #if UNITY_IPHONE || UNITY_IOS, т.к сюда по логике, кроме iOS этот постбилд не юзается, для метрики уже делал аналогичный pull request
https://github.com/yandexmobile/metrica-push-plugin-unity/pull/7/files

**Comment by OverF1Ow** [comment]
Прошло несколько месяцев, а воз и ныне там. Неужели так сложно добавить две строчки кода?
#if UNITY_IOS
...
#endif

**Comment by mobile-ads-github** [comment]
Здраствуйте! Подняли приоритет вашей задаче

**Comment by dreamcodestudio** [comment]
Как предложение начать использовать [ .asmdef](https://docs.unity3d.com/Manual/ScriptCompilationAssemblyDefinitionFiles.html)
в нашем случаи получилось разбить на
![image](https://user-images.githubusercontent.com/7010398/189496945-674aafc5-264b-4b27-a01d-d953610f6e74.png)
![image](https://user-images.githubusercontent.com/7010398/189496968-8bb94b7d-d214-416b-b0b9-5931b0464a2b.png)
это в том числе дает большой буст в компиляции больших проектов и избавляет от попадание лишнего кода в Runtime

**Comment by Andrew478** [comment]
Столкнулся с аналогичной проблемой! Уже ноябрь, а проблема так и не исправлена. Придётся ставить ненужный iOS build support. Надеюсь с этим данная проблема решится...

**Comment by mobile-ads-github** [comment]
Добрый день!
Исправление данной проблемы будет включено в следующий релиз.

**Comment by dreamcodestudio** [comment]
пофикшено в версии 2.4.0
