### ISSUE TITLE
Unity удаляет Resolved зависимости

### ISSUE THREAD

**Issue by VladislavGist** [yandexmobile/yandex-ads-unity-plugin#120]
Когда я делаю активной настройку Custom Main Gradle Template, то удаляются все зарезолвленные зависимости в папке Plugins/Android. При активных Custom Main Gradle Template и Custom Gradle Properties Template проект без разеролвленных зависимостей успешно билдится и демо реклама показывается. Вопрос, в итоге нужно как-то пытаться добавить в проект зависимости, которые были автоматически удалены Unity? (прикрепил видео)

P.S. Если чекбоксы выставить до импорта библиотеки и резолва зависимостей, то при билде проекта (под Android) Unity все равно удаляет почти все из папки Plugins/Android (остается как на видео)

Версия Unity: 2022.3.47f1
Версия yandex-mobileads-lite: 7.5.0

https://github.com/user-attachments/assets/e92bcd12-51b0-4b85-88af-a3ffeea96db7

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-3806. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-3806 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by integer222** [comment]
Это правильное поведение, зависимости ресолвер прописывает в файл mainTemplate.gradle.
Примерно Вот так 
implementation 'androidx.lifecycle:lifecycle-process:2.4.1'
implementation 'com.yandex.android:mobileads:7.5.0'
implementation 'com.yandex.android:mobmetricalib:5.2.0'

Это удобнее чем каждый раз выкачивать кучу зависимостей :)
