### ISSUE TITLE
Собранные приложения не запускаются

### ISSUE THREAD

**Issue by qwerty4921** [yandexmobile/yandex-ads-unity-plugin#122]
Здравствуйте, собранное приложение не запускается на телефонах моргает черный экран на доли секунды.
 При сборке ошибок нет, и не важно пустой проект или "рабочий".
Когда Custom Main Gradle Template  и Custom Gradle Properties Template выключаешь то проект работает 
Пробывал на Unity 2022.3.45 и Unity 2022.3.49 (minSdk 24 target 34/35) проверял на различных моделях телефона везде одинаковая ситуация.

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-3867. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-3867 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.
