### ISSUE TITLE
Проверка работоспособности адаптеров в сторонних сетях

### ISSUE THREAD

**Issue by Red-Cat-Fat** [yandexmobile/yandex-ads-unity-plugin#16]
Подключили адаптер Яндекса для показа в нашей игре на Unity через IronSource. Подключали путём интеграции библиотек для Android и iOS. Подключали в соответствии с документацией со страниц https://yandex.ru/dev/mobile-ads/doc/android/adapters/ironsource-adapter.html и https://yandex.ru/dev/mobile-ads/doc/ios/adapters/ironsource-adapter.html соответственно. Для обеих используется Yandex Mobile Ads SDK и удовлетворяющие требования версии IronSource для Android и iOS, путём подключения разных версий при сборке, чтобы попасть в требования адаптеров. 
Медиацию настроили, но при запуске рекламы из админки IS система не выдаёт рекламу. Просто "наролливая" рекламу в проекте - она никак не выпадает, причём ошибок никаких нет. Как можно проверить работоспособность адаптеров? Должна ли настройка из админки IS выдавать рекламу для кастомного адаптера?

**Comment by mobile-ads-github** [comment]
Здравствуйте. На данный момент в IS не поддержана проверка интеграции кастомных сетей медиации, в том числе и сети Yandex.
В будущих релизах адаптера мы добавим вывод в лог информации о корректности интеграции Yandex Mobile Ads.
