### ISSUE TITLE
Ошибка сборки под iOS на Mac M1

### ISSUE THREAD

**Issue by breakmt** [yandexmobile/yandex-ads-unity-plugin#21]
Пытаюсь собрать проект с РСЯ 2.1.1, но получаю кучу ошибок:
```
Undefined symbols for architecture arm64:
  "protocol conformance descriptor for Foundation.URL : Swift.Decodable in Foundation", referenced from:
      CommonCoreTiny.UserInterfaceAction.Payload.init(from: Swift.Decoder) throws -> CommonCoreTiny.UserInterfaceAction.Payload in YandexMobileAds(UserInterfaceAction.o)
  "static (extension in Swift):Swift.Optional<A where A: Swift.Equatable>.== infix(A?, A?) -> Swift.Bool", referenced from:
      static (extension in CommonCoreTiny):CommonCoreTiny.(ListNode in _4B48FEEA3FC11DA463D33FDF96A3AB1F)< where A: Swift.Equatable>.== infix(CommonCoreTiny.(ListNode in _4B48FEEA3FC11DA463D33FDF96A3AB1F)<A>, CommonCoreTiny.(ListNode in _4B48FEEA3FC11DA463D33FDF96A3AB1F)<A>) -> Swift.Bool in YandexMobileAds(UIElementPath.o)
```

Толком ничего не нагуглил, только совет исключить x64 из сборки. Я не могу делать сборку на М1 - в этом дело? или можно доработать сам плагин?

PS: без РСЯ плагина, но с Google Admob плагином всё окей. Удалил РСЯ до фикса.

**Comment by mobile-ads-github** [comment]
Добрый день, спасибо за обращение, разберемся.
Еще такой момент, при сборке у вас выставлено treat warnings as errors или нет?

**Comment by breakmt** [comment]
Спасибо, буду ждать. Treat warnings as errors стоит как No.

**Comment by mobile-ads-github** [comment]
This issue has been closed due to a lack of recent activity. If the problem is still relevant, please feel free to reopen the issue or comment with additional details. Thank you!
