### ISSUE TITLE
Нарушение правил Гугл плей

### ISSUE THREAD

**Issue by sbmgamescom** [yandexmobile/yandex-ads-unity-plugin#22]
Использую плагин под юнити, версия 2.1.0.

![image](https://user-images.githubusercontent.com/46422509/177177529-15b26d68-8be2-4446-8eba-7f0f195c055f.png)

**Comment by mobile-ads-github** [comment]
Здравствуйте,
В качестве временного решения можно подключить версию Апметрики 5.0.0 ( https://yandex.ru/dev/mobile-ads/doc/android/quick-start/android-ads-component.html implementation 'com.yandex.android:mobmetricalib:5.0.0' ). В следующем релизе плагина, с поддержкой Ads SDK 5.2.0, мы перейдем на эту версию, и проблема уйдет.

**Comment by mobile-ads-github** [comment]
Здравствуйте
Вышел релиз 2.2.0 с поддержкой Апметрики 5.0.0
