### ISSUE TITLE
Установка yandex-mobileads ломает другой популярный пакет на IOS

### ISSUE THREAD

**Issue by egorovsa** [yandexmobile/yandex-ads-unity-plugin#25]
После установки yandex-mobileads-lite-2.1.1 начинается крашится приложение при использовании пакета
[UnityNativeShare](https://github.com/yasirkula/UnityNativeShare)
Перед тем как прийти сюда я несколько раз все перепроверил и это воспроизводится 100%

в их репозитории я так же открыл Issue и описал данную проблему.

[UnityNativeShare -  Issue](https://github.com/yasirkula/UnityNativeShare/issues/147)

Я уже 3 дня бьюсь и не могу понять что с этим делать и как это решить.

**Comment by egorovsa** [comment]
Локализовал проблему, удалил вообще всё из пакета кроме  Editor/YandexMobileadsDependencies.xml
в нем оставил только 

```
<dependencies>
    <iosPods>
        <iosPod name="YandexMobileAds" version="5.1.0">
            <sources>
                <source>https://github.com/CocoaPods/Specs</source>
            </sources>
        </iosPod>
    </iosPods>
</dependencies>
```

Проблема сохранилась.
Удалив этот файл зависимостей, проблема исчезает.

**Comment by mobile-ads-github** [comment]
Добрый день. 
Спасибо большое за обращение и за дебаг. Увидели где проблема, будем исправлять.

**Comment by egorovsa** [comment]
Супер! Спасибо! Будем ждать выхода багфикса !

**Comment by egorovsa** [comment]
@mobile-ads-github здравствуйте, Нет ли подвижек в этом вопросе? Увидел новый релиз 3 дня назад, к сожалению он не решил проблему. =(

**Comment by mobile-ads-github** [comment]
Добрый день.
Спасибо большое за обращение.
Исправления попадут в следующий релиз.

**Comment by egorovsa** [comment]
Ребята привет . Дошли мои руки , все обновил проверил пересобрал. 
Все работает. Мерси бокуп! Можно закрыть!
