### ISSUE TITLE
Не отображаются баннеры

### ISSUE THREAD

**Issue by exe2k** [yandexmobile/yandex-ads-unity-plugin#33]
### Не работает отображение реальных баннеров в игре, при этом демо-баннера отображаются. 
Даже при использовании кода из [примера скрипта ](https://github.com/yandexmobile/yandex-ads-unity-plugin/blob/master/samples/YandexMobileAdsBannerDemoScript.cs) - не отображаются реальные баннеры, но демо-баннера работают.

**Скрипт возвращает ошибку «There are no ADs available», при этом Interstitial работают без проблем.** 
Модерация приложения, естественно, пройдена. 

Техподдержке сообщил, но пока решения именно под SDK для Unity не получил. Почти неделю уже пытаемся разобраться :( 
Из последних решений - выслали мне вариант загрузки напрямую из рекламных сетей, но на Kotlin (Android Studio), что мне, как разработчику на Unity (C#) не особо помогло((( 

Есть ли вариант рабочего скрипта для баннеров в Unity с данным SDK? 
Если это какая-то глобальная проблема с баннерами - есть ли какие-то (хотя бы примерные) сроки решения данной проблемы? 

Допускаю, что возможно я что-то сделал не так при интеграции, но ТП заверила, что на моей стороне проблемы нет.

**Баннера:** 
R-M-1956527-3  
R-M-1956527-1

_При этом изначально баннер R-M-1956527-3 работал первый день, затем перестал..._

Ошибка воспроизведена на 3х устройствах (Android 10,11,12)

**Comment by mobile-ads-github** [comment]
Здравствуйте, просим прощение за долгий ответ 
Поправили на своей стороне, статистика по блокам пошла, подтвердите пожалуйста, что вы тоже видете рекламу

**Comment by exe2k** [comment]
Здравствуйте, на почту вам ответил, но продублирую и тут - проблемы больше нет, спасибо!

**Comment by RustamBerkut** [comment]
Здравствуйте. У меня такая же проблема, тестовый показывает, когда ставлю свой код, то не идет реклама, код вставки баннера: R-M-5902938-2
