### ISSUE TITLE
Получаю CRASH при запуске приложения

### ISSUE THREAD

**Issue by Maskusa** [yandexmobile/yandex-ads-unity-plugin#37]
В Firebase Crashlytics приходят отчёты от пользователей с CRASH. Приложение вылетает при запуске. 
Подскажите как можно пофиксить или как поймать этот креш, чтобы пользователь мог войти в приложение?
Использую yandex-ads-unity-plugin 2.3.0

#
Stack trace Лог 1:

Device
Brand:unknown
Model:GCE x86 phone
Orientation: Portrait
RAM free: 6.04 GB
Disk free: 2.2 GB
Operating System
Version:Android 9
Orientation: Portrait
Rooted:Yes
Crash
Date:Nov 12, 2022, 2:47:53 PM
App version:1.2.138 (295)

`
Fatal Exception: java.lang.Error: FATAL EXCEPTION [UnityMain]
Unity version     : 2021.3.11f1
Device model      : unknown GCE x86 phone
Device fingerprint: generic/gce_x86_phone/gce_x86:9/PGR1.190916.001/5877764:userdebug/test-keys
Build Type        : Release
Scripting Backend : IL2CPP
ABI               : armeabi-v7a
Strip Engine Code : true
`

`
Caused by java.lang.Error: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Version '2021.3.11f1 (0a5ca18544bf)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'armeabi-v7a'
Build fingerprint: 'generic/gce_x86_phone/gce_x86:9/PGR1.190916.001/5877764:userdebug/test-keys'
Revision: '0'
ABI: 'arm'
Timestamp: 2022-11-12 03:47:52-0800
pid: 10790, tid: 11572, name: UnityMain  >>> com.subtit.player <<<
uid: 10093
signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x0
    r0  00000001  r1  d4e0cfc0  r2  00003435  r3  00000000
    r4  00000000  r5  00000001  r6  00000001  r7  bf297220
    r8  00000002  r9  bf29c17c  r10 00000000  r11 bf296cec
    ip  eeb562d0  sp  c287f3e0  lr  c84ef7ec  pc  00000000
`

`	Thread-5:
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor$(Thread.java:2137)
       at sun.misc.Unsafe.park(Unsafe.java:358)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2059)
       at java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:548)
       at com.yandex.mobile.ads.impl.of.a(SourceFile:2)
       at com.yandex.mobile.ads.impl.of.run(SourceFile:9)
`	   

Stack trace Лог 2:

Device
Brand:unknown
Model:GCE x86 phone
Orientation: Portrait
RAM free: 6.07 GB
Disk free: 2.21 GB
Operating System
Version:Android 9
Orientation: Portrait
Rooted:Yes
Crash
Date:Nov 12, 2022, 3:03:01 PM
App version:1.2.138 (295)

`
Fatal Exception: java.lang.Error: FATAL EXCEPTION [UnityMain]
Unity version     : 2021.3.11f1
Device model      : unknown GCE x86 phone
Device fingerprint: generic/gce_x86_phone/gce_x86:9/PGR1.190916.001/5877764:userdebug/test-keys
Build Type        : Release
Scripting Backend : IL2CPP
ABI               : armeabi-v7a
Strip Engine Code : true
`

`
Caused by java.lang.Error: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Version '2021.3.11f1 (0a5ca18544bf)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'armeabi-v7a'
Build fingerprint: 'generic/gce_x86_phone/gce_x86:9/PGR1.190916.001/5877764:userdebug/test-keys'
Revision: '0'
ABI: 'arm'
Timestamp: 2022-11-12 04:03:01-0800
pid: 8178, tid: 8803, name: UnityMain  >>> com.subtit.player <<<
uid: 10093
signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x0
    r0  00000001  r1  ce1b77c0  r2  00003435  r3  00000000
    r4  00000000  r5  00000001  r6  00000001  r7  bf797220
    r8  00000002  r9  bf79c17c  r10 00000000  r11 bf796cec
    ip  f1cd52d0  sp  c2c813e0  lr  c8a7c7ec  pc  00000000
`

`
YMM-DW-3:
       at java.lang.Object.wait(Object.java)
       at com.yandex.metrica.impl.ob.Ra$a.run(SourceFile:12)
`

**Comment by mobile-ads-github** [comment]
Добрый день. Можете, пожалуйста, сказать c какого потока вы загружаете рекламу? Мы поддерживаем только загрузку с главного потока

**Comment by Maskusa** [comment]
Думаю, что рекламу загружаю с главного потока, тк интегрирую рекламу по официальному гайду, и у большинства пользователей всё работает хорошо.
Этот сбой случился у 0,05% пользователей. Обычно это устройства "Model:GCE x86 phone"
