### ISSUE TITLE
Crash после добавления медиации AdMob

### ISSUE THREAD

**Issue by DDru** [yandexmobile/yandex-ads-unity-plugin#40]
Сначала добавил в игру на юнити обычную Яндекс рекламу, все работало. Потом добавил ассет с медиацией AdMob, зависимости автоматически обновились. После тестовой проверки на телефоне игры вылетает.
Использую yandex-ads-unity-plugin-2.4.0 и Unity 2022.1.23. Пробовал дополнительно по гугл инструкции добавлять идентификатор AdMob в манифест, но разницы нет.
![Screenshot_2022-11-28-06-04-28-954_com miui bugreport](https://user-images.githubusercontent.com/10414783/204288007-cf235de1-ff7e-4cbc-a49d-e646e4fd5f1b.jpg)
![Screenshot_2022-11-28-06-04-40-226_com miui bugreport](https://user-images.githubusercontent.com/10414783/204288020-ead17617-4032-4f92-8276-20c1e6c7a1d9.jpg)
![Screenshot_2022-11-28-06-04-46-924_com miui bugreport](https://user-images.githubusercontent.com/10414783/204288023-2b5c35ff-8143-4b37-bd83-b2a643e4766b.jpg)

**Comment by PolluxDevelopersTeam** [comment]
Admob и Яндекс.Реклама используют разные версии External Dependency Manager. Полностью (включая вышеуказанный менеджер зависимостей и файлы пакетов рекламы в Plugins/Android) удалите оба пакета, затем сначала добавьте пакет Admob, затем Яндекс.Рекламу, но в окне импорта Яндекс.Рекламы снимите галочку с папки ExternalDependencyManager. Если Unity на каком-то этапе спросит про обновление файлов, нажмите Да.

**Comment by DDru** [comment]
У меня до начала установки уже был Firebase с последней версией External Dependency Manager. Но ваш вариант проверил и все так же не работает.
И в контроле версий обновились только хеши у некоторых библиотек от Firebase.

**Comment by PolluxDevelopersTeam** [comment]
У меня на версиях Unity 2021 работают Firebase + Admob + Яндекс, все норм.

**Comment by DDru** [comment]
А можешь проверить пустой проект на Unity 2022.1?

**Comment by mobile-ads-github** [comment]
Добрый день! Для решения вашей проблемы нужно:

**Comment by DDru** [comment]
> Добрый день! Для решения вашей проблемы нужно:
> 
> 1. Cделать File -> Build Settings -> Android -> Player Settings -> Publishing settings -> Custom Main Manifest
> 2. В появившемся xml добавить
> 
> ```
> <manifest>
>     <application>
> ...
>         <meta-data
>             android:name="com.google.android.gms.ads.APPLICATION_ID"
>             android:value="ca-app-pub-xxxxxxxxxxxxxxxx~yyyyyyyyyy"/>
> ...
>     </application>
> </manifest>
> ```

Вроде все так сделал, но что-то не помогло. А вы сами проверяли в приложении или это репост из гугл документации? Может в интеграции какой-то баг.

**Comment by DDru** [comment]
Это была моя ошибка. Из-за не знания как работать с манифестом я вставлял мета строки в раздел
```
<manifest
    <application>
        <activity
               // мета - инициализация
```
А нужно просто в "application"
```
<manifest
    <application>
            // мета - инициализация
```

**Comment by sakura-gamedev** [comment]
@mobile-ads-github У меня такая же ошибка, только с учётом того, что AdMob нигде не используется, как и Firebase. Манифест исправлен, но ошибка всё также появляется. Из зависимостей помимо яндекса только Amplitude и Facebook. 

Версия Unity 2021.3.16
Версия плагина 2.7.0
Dependecy Resolver 1.2.175(latest)

Манифест
```
<?xml version="1.0" encoding="utf-8"?>
<manifest
    xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.unity3d.player"
    xmlns:tools="http://schemas.android.com/tools">
    <application>
        <activity android:name="com.unity3d.player.UnityPlayerActivity"
                  android:theme="@style/UnityThemeSelector">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
            <meta-data android:name="unityplayer.UnityActivity" android:value="true" />
            <meta-data
                    android:name="com.google.android.gms.ads.APPLICATION_ID"
                    android:value="ca-app-pub-xxxxxxxxxxxxxxxx~yyyyyyyyyy"/>
        </activity>
    </application>
    <uses-permission android:name="com.google.android.gms.permission.AD_ID"/>
</manifest>
```
