### ISSUE TITLE
Error Unity Exception: ... onImpression()

### ISSUE THREAD

**Issue by Maskusa** [yandexmobile/yandex-ads-unity-plugin#41]
При показе баннера рекламы я получаю сообщение в журнал об ошибке
2022.12.04 01:47:21.454 Error Unity Exception: No such proxy method: YandexMobileAds.Platforms.Android.BannerClient.onImpression()

Всё работает хорошо, но хотелось бы узнать, почему это происходит и нормальная ли это ситуация?

В проекте установлены sdk: GoogleAds, GoogleAdsNative, YandexAds

**Comment by mobile-ads-github** [comment]
Добрый день! В новой версии мы рекомедуем использовать метод `public void onImpression(string rawImpressionData)` для получения данных об импрешенне. https://yandex.ru/dev/mobile-ads/doc/plugins/unity/ref/banner-class.html#event_detail__event_onImpression

**Comment by PolluxDevelopersTeam** [comment]
Тоже появляется такое исключение в логе после показа рекламы (не баннерная). Это исключение начало появляться с версии 2.4.0. Это нормально или надо как-то фиксить?

**Comment by Maskusa** [comment]
> Добрый день! В новой версии мы рекомедуем использовать метод `public void onImpression(string rawImpressionData)` для получения данных об импрешенне. https://yandex.ru/dev/mobile-ads/doc/plugins/unity/ref/banner-class.html#event_detail__event_onImpression


Я использую новую(последнюю) версию плагина: Release 2.5.0 lite
Ваша рекомендация **не работоспособна**, почему вы мне её рекомендовали? Я настраиваю показ согласно официальной документации:
![bug_OnImpr_3](https://user-images.githubusercontent.com/36055412/207744010-567ada25-ebbb-4122-9ddf-8d0646d87fc3.png)
![bug_OnImpr_4](https://user-images.githubusercontent.com/36055412/207744014-7afb912c-2310-4775-b9b8-c1fd71530cd9.png)

При этом получаю кучу ошибок : 
`Error Unity Exception: No such proxy method: YandexMobileAds.Platforms.Android.BannerClient.onImpression()`

Вот мои настройки:

```
mainTemplate.gradle

    implementation 'com.yandex.ads.mediation:mobileads-admob:21.3.0.0' // Assets/YandexMobileAds/Editor/MobileadsAdmobMediationDependencies.xml:12
    implementation 'com.yandex.android:mobileads:5.4.0' // Assets/YandexMobileAds/Editor/YandexMobileadsDependencies.xml:7
    implementation 'com.yandex.android:mobmetricalib:5.0.0' // Assets/YandexMobileAds/Editor/YandexMobileadsDependencies.xml:12
```
![bug_OnImpr_1](https://user-images.githubusercontent.com/36055412/207743536-f5e25adc-eb9f-4067-b730-54823a48e43a.png)

При изменении кода согласно вашей рекомендации, появляется ошибка, которая уходит в скрипты YandexMobileAds, куда мне точно лезть не нужно...
![bug_OnImpr_2](https://user-images.githubusercontent.com/36055412/207743538-7c81d09d-427b-46d9-8b1b-e18b9161583d.png)

Скрипт SDK YandexMobileAds: Assets\YandexMobileAds\Banner.cs
![bug_OnImpr_5](https://user-images.githubusercontent.com/36055412/207744342-a10d3bd9-afe8-420a-adcd-45959b7ad45e.png)
![bug_OnImpr_6](https://user-images.githubusercontent.com/36055412/207744346-340e1c6d-1112-47c4-9a53-ff32ed9b1344.png)

**Comment by mobile-ads-github** [comment]
Добрый день, спасибо за репорт об ошибке! Обнаружили проблему, в следующей версии 2.6.0 исправим, планируем релиз до Нового года.
Вам нужно будет только обновить плагин, менять в коде ничего не нужно.
