### ISSUE TITLE
Не удаляются баннеры после перезагрузки сцены

### ISSUE THREAD

**Issue by DDru** [yandexmobile/yandex-ads-unity-plugin#45]
Создал баннер как указанно в скрипте с примером и удалением его в методе OnDestroy(). Но после перезагрузки сцены старый баннер остается, а поверх него создается новый. При продолжении перезагрузки сцены баннеры продолжают наслаиваться друг на друга. 
Версия юнити 2022.2.1f1

Временно решил проблему сделав класс синглтоном и не удаляемым (через DontDestroyOnLoad()). Так при перезагрузке сцены можно через переменную узнать существует ли уже баннер или нет.

**Comment by mobile-ads-github** [comment]
Добрый день! Уточните, пожалуйста, как Вы создаете баннер?
Вполне вероятно, Вы создаете и загружаете баннер два раза подряд, поэтому теряется ссылка на первый объект, что продуцирует данную проблему. Рекомендуется в методе загрузки баннера проверять создан ли уже баннер и вызывать у него метод destroy() как показано в нашем [демоскрипте](https://github.com/yandexmobile/yandex-ads-unity-plugin/blob/master/samples/YandexMobileAdsBannerDemoScript.cs#L62).

**Comment by integer222** [comment]
Такая же проблема 2022.2.1f, версия 2.6.0
При удаление баннера происходит ошибка и баннер не удаляется
`2023.01.17 23:26:45.831 20683 20756 Error Unity AndroidJavaException: java.lang.NoSuchMethodError: no non-static method with name='setUnityBannerListener' signature='()V' in class Ljava.lang.Object;
2023.01.17 23:26:45.831 20683 20756 Error Unity java.lang.NoSuchMethodError: no non-static method with name='setUnityBannerListener' signature='()V' in class Ljava.lang.Object;
2023.01.17 23:26:45.831 20683 20756 Error Unity 	at com.unity3d.player.ReflectionHelper.getMethodID(Unknown Source:165)
2023.01.17 23:26:45.831 20683 20756 Error Unity 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
2023.01.17 23:26:45.831 20683 20756 Error Unity 	at com.unity3d.player.UnityPlayer.-$$Nest$mnativeRender(Unknown Source:0)
2023.01.17 23:26:45.831 20683 20756 Error Unity 	at com.unity3d.player.UnityPlayer$C$a.handleMessage(Unknown Source:95)
2023.01.17 23:26:45.831 20683 20756 Error Unity 	at android.os.Handler.dispatchMessage(Handler.java:102)
2023.01.17 23:26:45.831 20683 20756 Error Unity 	at android.os.Looper.loopOnce(Looper.java:226)
2023.01.17 23:26:45.831 20683 20756 Error Unity 	at android.os.Looper.loop(Looper.java:313)
2023.01.17 23:26:45.831 20683 20756 Error Unity 	at com.unity3d.player.UnityPlayer$C.run(Unknown Source:24)
2023.01.17 23:26:45.831 20683 20756 Error Unity   at UnityEngine._AndroidJNIHelper.GetMethodID (System.IntPtr jclass, System.String methodName, System.String signature, System.Boolean isStatic) [0x00000] in <00000000000000000000000000000000>:0 

`

Код 
private void InitBanner()
{
     _banner?.Destroy();
     var bannerMaxSize = AdSize.FlexibleSize(GetScreenWidthDp(), 50);
     _banner = new Banner(_id, bannerMaxSize, AdPosition.BottomCenter);
     _banner.OnAdLoaded += BannerOnAdLoaded;
     _banner.OnAdFailedToLoad += BannerOnAdFailedToLoad;
     _banner.LoadAd(new AdRequest.Builder().Build());
}

**Comment by integer222** [comment]
Проблема возникает только 2022.2.1f1. 
Откатился до версии Unity 2021.3.16f1 LTS проблема исчезла. @DDru возможно и тебе поможет

**Comment by mobile-ads-github** [comment]
@DDru, добрый день! Подскажите, проблема еще актуальна?

**Comment by mobile-ads-github** [comment]
Добрый день правки вышли в релизе 2.7.0
