### ISSUE TITLE
Unity 2022.2.5 + yandex ads 2.6.0 = одноразовый показ рекламы

### ISSUE THREAD

**Issue by OverF1Ow** [yandexmobile/yandex-ads-unity-plugin#48]
Обновил Unity до 2022.2.5, обновил sdk и теперь реклама с вознаграждением загружается только один раз и всё. Думал проблема у меня, но создал чистый проект, добавил YandexMobileAdsRewardedAdDemoScript.cs и проблема осталась. Нажимаю кнопку Request Rewarded Ad, затем Show Rewarded Ad и происходит показ рекламы, после этого никакой реакции на нажатие кнопки, ни Destroy, ни Request. На версии Unity 2021.3.17 всё работает корректно.

**Comment by denis22718** [comment]
Точно такая же проблема

**Comment by OverF1Ow** [comment]
> Точно такая же проблема

Поздравляю, теперь будем три года ждать пока исправят. Даже не удосужились хоть что-то ответить, ни здесь ни в техподдержке. Такого "замечательного" отношения к разработчикам нигде не встречал.

**Comment by mobile-ads-github** [comment]
Добрый день!
Спасибо за обращение. 
Подскажите, такое поведение наблюдается на какой то определенной платформе, или на обеих?
Вы также указали, что на версии Unity 2021.3.17 всё работает корректно. Я правильно понимаю, что при использовании sdk 2.6.0 + Unity 2021.3.17 всё работает корректно, а при обновлении Unity до более новой версии (2022.2.5) появляется проблема с Rewarded?

**Comment by OverF1Ow** [comment]
> Добрый день! Спасибо за обращение. Подскажите, такое поведение наблюдается на какой то определенной платформе, или на обеих? Вы также указали, что на версии Unity 2021.3.17 всё работает корректно. Я правильно понимаю, что при использовании sdk 2.6.0 + Unity 2021.3.17 всё работает корректно, а при обновлении Unity до более новой версии (2022.2.5) появляется проблема с Rewarded?

Платформа Android. Да, на старой версии Юнити всё работает. На 2022.2.5, 2022.2.4, 2022.2.3 точно не работает.

**Comment by OverF1Ow** [comment]
Вот, собственно, что вызывает ошибку, вытащил с девайса:

**Comment by mobile-ads-github** [comment]
Спасибо, разбираемся и постараемся исправить в ближайших версиях

**Comment by dreamcodestudio** [comment]
В релизе 2.7.0 проблема осталась
Unity 2021.3.14f1
делаю проверку по таймеру
``` c#
         private async UniTask RefreshAds()
        {
            const double delay = 3;
            while (!_adsCancellationToken.IsCancellationRequested)
            {
                if (!_rewardedAd.IsLoaded())
                    LoadRewardedAd();
                await UniTask.Delay(TimeSpan.FromSeconds(delay), cancellationToken: _adsCancellationToken.Token);
            }
        }
```
ответ приходит что реклама успешно загружена IsLoaded=true, но при вызове показывается 1 раз, при повторном Show рекламы нет

``` c#
        public void ShowRewardedVideo()
        {
            if (_rewardedAd.IsLoaded())
            {
                _rewardedAd.Show();
            }
            else
            {
                Debug.Log("Rewarded ad is not ready yet");
                OnAdsFinishFailure?.Invoke();
            }
        }
```

**Comment by dreamcodestudio** [comment]
нашел в чем именно проблема, после успешного показа экземпляр
`_rewardedAd.IsLoaded()`
возвращает всегда true, хотелось бы чтобы флаг обновлялся после показа, либо явно указать в документация что для повторной загрузки рекламы необходимо делать` Destroy()` рекламы
т.к  во внешних SDK, например GoogleAds или UnityAds. позволяется использовать тот же экземпляр для повторной загрузки рекламы, без повторного создания конструктора
--- для YandexMobileAds приходится использовать конструкцию вида
```
        private void LoadRewardedAd()
        {
            _rewardedAd?.Destroy();
            
            const string rewardedAdUnit = "R-M-DEMO-rewarded-client-side-rtb";
            _rewardedAd = new RewardedAd(rewardedAdUnit);
            _rewardedAd.OnRewardedAdLoaded += OnRewardedAdLoaded;
            _rewardedAd.OnRewardedAdFailedToLoad += OnRewardedAdFailedToLoad;
            _rewardedAd.OnRewarded += OnRewardAdCompleted;
            _rewardedAd.OnRewardedAdFailedToShow += OnRewardedAdFailedToShow;
            _rewardedAd.OnRewardedAdDismissed += OnRewardedAdDismissed;
            
            var adRequest = new AdRequest.Builder().Build();
            _rewardedAd.LoadAd(adRequest);
        }
```

**Comment by OverF1Ow** [comment]
На 2.7.0 заработало корректно. Спасибо за исправление.
