### ISSUE TITLE
Не показывает рекламу

### ISSUE THREAD

**Issue by JasonBrodyHM** [yandexmobile/yandex-ads-unity-plugin#53]
После обновления до 2.7 плагин начал работать, а вот реклама так и не начала показываться
![image_2023-02-21_17-21-25](https://user-images.githubusercontent.com/86774139/220734873-ce9ce803-a6be-4b10-92a5-666b7eab16e5.png)

**Comment by mobile-ads-github** [comment]
Спасибо за репорт. А можете проверить, будет ли реклама показываться если снять галку Development Build?
На скриншоте не видно логов загрузки рекламы. Какой именно рекламный формат Вы хотите проверить? Вы используете демо-блок или свой блок? Можете прислать код?

**Comment by JasonBrodyHM** [comment]
Вот весь лог после убирания галочки с DB:
2023.02.24 01:02:40.989 15687 15687 Error com.sarander Not starting debugger since process cannot load the jdwp agent.
2023.02.24 01:02:41.007 15687 15687 Debug os.typeface Already set agent. fontPath:null fontHash:
2023.02.24 01:02:41.010 15687 15687 Debug os.typeface Already set agent. fontPath:null fontHash:
2023.02.24 01:02:41.025 15687 15687 Debug os.typeface Already set agent. fontPath:null fontHash:
2023.02.24 01:02:41.031 15687 15687 Info LoadedApk No resource references to update in package com.transsion.theme.icon
2023.02.24 01:02:41.045 15687 15687 Debug os.typeface Already set agent. fontPath:null fontHash:
2023.02.24 01:02:41.052 15687 15687 Debug os.typeface Already set agent. fontPath:null fontHash:
2023.02.24 01:02:41.055 15687 15712 Info AppMetrica Initializing of Metrica, Release type, Version 5.0.0, API Level 105, Dated 18.05.2022.
0001.01.01 00:00:00.000 -1 -1 Info  --------- beginning of system
2023.02.24 01:02:41.064 15687 15687 Debug AppTurboService initialize
2023.02.24 01:02:41.066 15687 15687 Debug AppTurboService  mAppTurboTouchSlop = 0 mIsTpTurboApp = false
2023.02.24 01:02:41.066 15687 15687 Debug AppTurboService  getSettingSupport resullt = false mSettingCloudEnable = true
2023.02.24 01:02:41.069 15687 15715 Warn com.sarander Class com.yandex.metrica.impl.ob.Ni failed lock verification and will run slower.
2023.02.24 01:02:41.069 15687 15715 Warn com.sarander Common causes for lock verification issues are non-optimized dex code
2023.02.24 01:02:41.069 15687 15715 Warn com.sarander and incorrect proguard optimizations.
2023.02.24 01:02:41.084 15687 15714 Info AppMetrica Activate reporter with APIKey 20799a27-xxxx-xxxx-xxxx-xxxxxxxx4180
2023.02.24 01:02:41.096 15687 15687 Info IL2CPP JNI_OnLoad
2023.02.24 01:02:41.098 15687 15687 Info SurfaceFactory [static] sSurfaceFactory = com.mediatek.view.impl.SurfaceFactoryImpl@9a233e7
2023.02.24 01:02:41.103 15687 15726 Debug ActivityThreadLice received OSMessage 110001
2023.02.24 01:02:41.103 15687 15726 Debug ActivityThreadLice send OSMessage 110001 to [-1]
2023.02.24 01:02:41.105 15687 15726 Debug OSServiceManager update local os service os.activity from null to android.os.BinderProxy@18aab94
2023.02.24 01:02:41.119 15687 15687 Info os.InputLice create InputLice
2023.02.24 01:02:41.119 15687 15687 Info os.triplefingerscreenshot create instance:true
2023.02.24 01:02:41.116 15687 15687 Warn com.sarander type=1400 audit(0.0:436): avc: denied { read } for name="u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=14024 scontext=u:r:untrusted_app:s0:c45,c257,c512,c768 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=0
2023.02.24 01:02:41.120 15687 15687 Warn com.sarander type=1400 audit(0.0:437): avc: denied { read } for name="u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=14024 scontext=u:r:untrusted_app:s0:c45,c257,c512,c768 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=0
2023.02.24 01:02:41.121 15687 15687 Error libc Access denied finding property "ro.vendor.scaler_version"
2023.02.24 01:02:41.122 15687 15687 Error libc Access denied finding property "ro.vendor.scaler_version"
2023.02.24 01:02:41.132 15687 15687 Info InputTransport Create ARC handle: 0xd3fbfd10
2023.02.24 01:02:41.134 15687 15687 Verbose PhoneWindow DecorView setVisiblity: visibility = 0, Parent = android.view.ViewRootImpl@930ed00, this = DecorView@b1939[UnityPlayerActivity]
2023.02.24 01:02:41.150 15687 15712 Debug Volley [86] fu0.a: Changing log tag to Yandex Mobile Ads
2023.02.24 01:02:41.157 15687 15712 Debug NetworkSecurityConfig No Network Security Config specified, using platform default
2023.02.24 01:02:41.160 15687 15687 Debug Surface lockCanvas
2023.02.24 01:02:41.160 15687 15687 Debug Surface Surface::connect(this=0xea336000,api=2)
2023.02.24 01:02:41.162 15687 15687 Warn Gralloc3 mapper 3.x is not supported
2023.02.24 01:02:41.165 15687 15687 Error gralloc Arm Module v1.0
2023.02.24 01:02:41.166 15687 15687 Error ion ioctl c0044901 failed with code -1: Invalid argument
2023.02.24 01:02:41.177 15687 15712 Info YandexAdsIntegrityCheck Yandex Mobile Ads 5.5.1 initialized successfully
2023.02.24 01:02:41.187 15687 15687 Debug Surface lockCanvas
2023.02.24 01:02:41.210 15687 15723 Info Unity MemoryManager: Using 'Dynamic Heap' Allocator.
2023.02.24 01:02:41.230 15687 15723 Info Unity SystemInfo CPU = ARM64 FP ASIMD AES, Cores = 8, Memory = 3803mb
2023.02.24 01:02:41.230 15687 15723 Info Unity SystemInfo ARM big.LITTLE configuration: 2 big (mask: 0xc0), 6 little (mask: 0x3f)
2023.02.24 01:02:41.231 15687 15723 Info Unity ApplicationInfo com.sarander version 1.7
2023.02.24 01:02:41.231 15687 15723 Info Unity Built from '2021.3/staging' branch, Version '2021.3.16f1 (4016570cf34f)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'armeabi-v7a', Stripping 'Enabled'
2023.02.24 01:02:41.300 15687 15723 Error libprocessgroup set_timerslack_ns write failed: Operation not permitted
2023.02.24 01:02:41.300 15687 15723 Info chatty uid=10301(com.sarander) UnityMain identical 14 lines
2023.02.24 01:02:41.301 15687 15723 Error libprocessgroup set_timerslack_ns write failed: Operation not permitted
2023.02.24 01:02:41.311 15687 15723 Info Unity Company Name: Sarander
2023.02.24 01:02:41.311 15687 15723 Info Unity Product Name: Just and easy note
2023.02.24 01:02:41.314 15687 15723 Debug vulkan searching for layers in '/data/app/com.sarander-2lNCja9GBXy4swDNJiHQZg==/lib/arm'
2023.02.24 01:02:41.314 15687 15723 Debug vulkan searching for layers in '/data/app/com.sarander-2lNCja9GBXy4swDNJiHQZg==/base.apk!/lib/armeabi-v7a'
2023.02.24 01:02:41.318 15687 15723 Info GPUD @gpudInitialize: successfully initialized with VK, dbg=0 mmdump_dbg=0 mmpath_dbg=0
2023.02.24 01:02:41.350 15687 15723 Debug Surface Surface::setBuffersUserDimensions(this=0xbdb9b000,w=720,h=1560)
2023.02.24 01:02:41.350 15687 15723 Debug Surface Surface::connect(this=0xbdb9b000,api=1)
2023.02.24 01:02:41.354 15687 15723 Debug Surface Surface::disconnect(this=0xbdb9b000,api=1)
2023.02.24 01:02:41.354 15687 15723 Debug Surface Surface::connect(this=0xbdb9b000,api=1)
2023.02.24 01:02:41.354 15687 15723 Debug Surface Surface::setBufferCount(this=0xbdb9b000,bufferCount=0)
2023.02.24 01:02:41.355 15687 15723 Debug Surface Surface::setBufferCount(this=0xbdb9b000,bufferCount=3)
2023.02.24 01:02:41.369 15687 15814 Info SwappyDisplayManager Starting looper thread
2023.02.24 01:02:41.369 15687 15723 Verbose SwappyVk SwappyVk initialized for VkDevice 0xb5a83000 using VK_GOOGLE_display_timing on Android
2023.02.24 01:02:41.370 15687 15723 Info SwappyVk Returning refresh duration of 16666667 nsec (approx 59.999999 Hz)
2023.02.24 01:02:41.375 15687 15723 Verbose MediaRouter Selecting route: RouteInfo{ name=Телефон, description=null, status=null, category=RouteCategory{ name=Система types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO  groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
2023.02.24 01:02:41.405 15687 15723 Debug   PlayerBase::PlayerBase()
2023.02.24 01:02:41.406 15687 15723 Debug   TrackPlayerBase::TrackPlayerBase()
2023.02.24 01:02:41.406 15687 15723 Info libOpenSLES Emulating old channel mask behavior (ignoring positional mask 0x3, using default mask 0x3 based on channel count of 2)
2023.02.24 01:02:41.406 15687 15723 Debug AudioTrack set(): 0xd409b680, streamType 3, sampleRate 48000, format 0x1, channelMask 0x3, frameCount 0, flags #104, notificationFrames -8, sessionId 113, transferType 0, uid -1, pid -1
2023.02.24 01:02:41.406 15687 15723 Debug AudioTrack set(): 0xd409b680, Create AudioTrackThread, tid = 15816
2023.02.24 01:02:41.410 15687 15723 Info AudioTrack createTrack_l(0): AUDIO_OUTPUT_FLAG_FAST successful; frameCount 0 -> 2048
2023.02.24 01:02:41.410 15687 15723 Debug AudioTrack createTrack_l(29): 0xd409b680, mCblk = 0xafd46000, mLatency = 94, mAfLatency = 52, frameCount = 2048, mSampleRate = 48000, mFlags = 0x4, mReqFrameCount = 2048, mNotificationFramesAct = 256
2023.02.24 01:02:41.411 15687 15723 Debug AudioTrack start(29): 0xd409b680, prior state:STATE_STOPPED
2023.02.24 01:02:41.412 15687 15687 Verbose MediaRouter Selecting route: RouteInfo{ name=Телефон, description=null, status=null, category=RouteCategory{ name=Система types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO  groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
2023.02.24 01:02:41.482 15687 15814 Info SwappyDisplayManager Terminating looper thread
2023.02.24 01:02:41.483 15687 15723 Debug Surface Surface::disconnect(this=0xbdb9b000,api=1)
2023.02.24 01:02:41.485 15687 15723 Debug Surface Surface::setBuffersUserDimensions(this=0xbdb9b000,w=720,h=1560)
2023.02.24 01:02:41.485 15687 15723 Debug Surface Surface::connect(this=0xbdb9b000,api=1)
2023.02.24 01:02:41.487 15687 15723 Debug Surface Surface::disconnect(this=0xbdb9b000,api=1)
2023.02.24 01:02:41.488 15687 15723 Debug Surface Surface::connect(this=0xbdb9b000,api=1)
2023.02.24 01:02:41.488 15687 15723 Debug Surface Surface::setBufferCount(this=0xbdb9b000,bufferCount=0)
2023.02.24 01:02:41.488 15687 15723 Debug Surface Surface::setBufferCount(this=0xbdb9b000,bufferCount=3)
2023.02.24 01:02:41.500 15687 15821 Info SwappyDisplayManager Starting looper thread
2023.02.24 01:02:41.500 15687 15723 Verbose SwappyVk SwappyVk initialized for VkDevice 0xb5a83000 using VK_GOOGLE_display_timing on Android
2023.02.24 01:02:41.500 15687 15723 Info SwappyVk Returning refresh duration of 16666667 nsec (approx 59.999999 Hz)
2023.02.24 01:02:41.548 15687 15822 Info IL2CPP Locale ru-RU
2023.02.24 01:02:41.578 15687 15723 Info GPUD @gpudInitialize: successfully initialized with GPUD, dbg=0 mmdump_dbg=0 mmpath_dbg=0
2023.02.24 01:02:41.686 15687 15687 Debug Surface lockCanvas
2023.02.24 01:02:43.574 15687 15723 Info Unity Initialization
2023.02.24 01:02:43.574 15687 15723 Info Unity UnityEngine.Logger:Log(LogType, Object)
2023.02.24 01:02:43.574 15687 15723 Info Unity AppEntryPoint:OnLoad()
2023.02.24 01:02:43.574 15687 15723 Info Unity 
2023.02.24 01:02:43.605 15687 15714 Info AppMetrica Activate reporter with APIKey 478cb909-xxxx-xxxx-xxxx-xxxxxxxx9f93
2023.02.24 01:02:43.617 15687 15687 Debug os.typeface Already set agent. fontPath:null fontHash:
2023.02.24 01:02:43.618 15687 15687 Info WebViewFactory Loading com.google.android.webview version 108.0.5359.79 (code 535907933)
2023.02.24 01:02:43.652 15687 15687 Info cr_WVCFactoryProvider Loaded version=108.0.5359.79 minSdkVersion=29 isBundle=true multiprocess=true packageId=2
2023.02.24 01:02:43.661 15687 15687 Info cr_LibraryLoader Successfully loaded native library
2023.02.24 01:02:43.661 15687 15687 Info cr_CachingUmaRecorder Flushed 8 samples from 8 histograms.
2023.02.24 01:02:43.790 15687 15883 Debug WifiManager updateRssiLevelFormService----isWifiRssiLevelUpdate=true----mWifiRssiLevel=null----mContext.getOpPackageName()=com.sarander
2023.02.24 01:02:43.799 15687 15883 Debug Yandex Mobile Ads [133] fu0.a: Changing log tag to Yandex Mobile Ads
2023.02.24 01:02:43.809 15687 15890 Info System.out [okhttp]:check permission begin!
2023.02.24 01:02:43.809 15687 15890 Warn System ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
2023.02.24 01:02:43.809 15687 15890 Info System.out [okhttp] e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaUtils
2023.02.24 01:02:43.884 15687 15890 Info System.out [socket]:check permission begin!
2023.02.24 01:02:43.884 15687 15890 Warn System ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
2023.02.24 01:02:43.884 15687 15890 Info System.out [socket] e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaUtils
2023.02.24 01:02:44.123 15687 15890 Info System.out [OkHttp] sendRequest>>
2023.02.24 01:02:44.123 15687 15890 Info System.out [OkHttp] sendRequest<<
2023.02.24 01:02:44.375 15687 15890 Error Yandex Mobile Ads [138] nd.a: Unexpected response code 403 for https://mobile.yandexadexchange.net/v4/ad
Использую свой блок для реварда, в предыдущей версии он работал.

**Comment by JasonBrodyHM** [comment]
using System;
using YandexMobileAds;
using YandexMobileAds.Base;

namespace Script
{
    public sealed class YandexAdsManager
    {
        private static readonly string _adUnitId = "R-M-2110309-1";
        
        private static YandexAdsManager _instance;

        public static YandexAdsManager Instance => _instance;
        
        public static void Initialize()
        {
            _instance = new YandexAdsManager();
        }

        private readonly RewardedAd _rewardedAd;

        private Action<bool> _adsCallback;

        public bool IsLoaded => _rewardedAd.IsLoaded();

        public event Action OnAdvertisementLoad;
        public event Action<bool> OnAdvertisementShowed;

        private YandexAdsManager()
        {
            _rewardedAd = new RewardedAd(_adUnitId);
            _rewardedAd.OnRewardedAdLoaded += HandleRewardedAdLoaded;
            _rewardedAd.OnRewardedAdFailedToLoad += HandleRewardedAdFailedToLoad;
            _rewardedAd.OnRewarded += HandleRewarded;
            _rewardedAd.OnRewardedAdFailedToShow += HandleRewardedAdFailedToShow;

            AdRequest adRequest = CreateRequest();
            _rewardedAd.LoadAd(adRequest);
        }

        public void ShowAdvertisement(Action<bool> callback)
        {
            if (IsLoaded)
            {
                _adsCallback = callback;
                _rewardedAd.Show();
            }
            else
            {
                callback?.Invoke(false);
            }
        }

        private void HandleRewardedAdLoaded(object sender, EventArgs eventArgs)
        {
            OnAdvertisementLoad?.Invoke();
        }
        
        private void HandleRewardedAdFailedToLoad(object sender, AdFailureEventArgs eventArgs)
        {
            AdRequest adRequest = CreateRequest();
            _rewardedAd.LoadAd(adRequest);
        }

        private void HandleRewarded(object sender, Reward reward)
        {
            Action<bool> callback = _adsCallback;
            _adsCallback = null;
            
            callback?.Invoke(true);
            
            AdRequest adRequest = CreateRequest();
            _rewardedAd.LoadAd(adRequest);
            
            OnAdvertisementShowed?.Invoke(true);
        }

        private void HandleRewardedAdFailedToShow(object sender, AdFailureEventArgs adFailureEventArgs)
        {
            Action<bool> callback = _adsCallback;
            _adsCallback = null;
            
            callback?.Invoke(false);
            
            AdRequest adRequest = CreateRequest();
            _rewardedAd.LoadAd(adRequest);
            
            OnAdvertisementShowed?.Invoke(false);
        }

        private static AdRequest CreateRequest()
        {
            var builder = new AdRequest.Builder();
            return builder.Build();
        }

    }
}

**Comment by mobile-ads-github** [comment]
Спасибо за предоставленную информацию. Проверьте, совпадает ли bundle id приложения с тем что Вы указали в Партнерском интерфейсе

**Comment by JasonBrodyHM** [comment]
Проблема решена все работает

**Comment by mobile-ads-github** [comment]
Рады, что у Вас все заработало!
Можете уточнить - дело было в несовпадении bundle id?
