### ISSUE TITLE
Ошибка сборки под iOS на Mac M1

### ISSUE THREAD

**Issue by dethroneofall** [yandexmobile/yandex-ads-unity-plugin#58]
Создал новый проект, добавил lite версию как по туториалу, но при билде в xcode вылетают ошибки , что это за ошибки ?
Спасибо
![image (1)](https://user-images.githubusercontent.com/19860525/235465113-e83a0f01-69bc-415d-9c78-a6309e23a59c.png)
![image](https://user-images.githubusercontent.com/19860525/235465117-72403381-afb2-419f-97a4-518f1db239dd.png)

**Comment by mobile-ads-github** [comment]
Здраствуйте.
Попробуйте почистить папку DerivedData и перебилидить проект в xcode

**Comment by dethroneofall** [comment]
Добрый день, очистил, не помогло 
прикрепил лог с ошибками, возможно поможет, почему не хочет линковаться 
[Build target UnityFramework_2023-05-02T15-43-17.txt](https://github.com/yandexmobile/yandex-ads-unity-plugin/files/11373517/Build.target.UnityFramework_2023-05-02T15-43-17.txt)

**Comment by dethroneofall** [comment]
> 

Добрый день, очистил, не помогло
прикрепил лог с ошибками, возможно поможет, почему не хочет линковаться
[Build target UnityFramework_2023-05-02T15-43-17.txt](https://github.com/yandexmobile/yandex-ads-unity-plugin/files/11373532/Build.target.UnityFramework_2023-05-02T15-43-17.txt)

**Comment by dethroneofall** [comment]
> Здраствуйте. Попробуйте почистить папку DerivedData и перебилидить проект в xcode

Добрый день, очистил, не помогло
прикрепил лог с ошибками, возможно поможет, почему не хочет линковаться
[Build target UnityFramework_2023-05-02T15-43-17.txt](https://github.com/yandexmobile/yandex-ads-unity-plugin/files/11373536/Build.target.UnityFramework_2023-05-02T15-43-17.txt)

**Comment by mobile-ads-github** [comment]
Я же правильно понимаю что проблема возникает на абсолютно чистом проекте ?  Можете залить его на гитхаб ? У нас не получается воспроизвести на новом проекте

**Comment by dethroneofall** [comment]
Да, конечно
https://bitbucket.org/kirovvyacheslav/testyandexads/src/master/
Может не подкачалось что то через VPN

**Comment by dethroneofall** [comment]
> Я же правильно понимаю что проблема возникает на абсолютно чистом проекте ? Можете залить его на гитхаб ? У нас не получается воспроизвести на новом проекте

Да, конечно
https://bitbucket.org/kirovvyacheslav/testyandexads/src/master/
Может не подкачалось что то через VPN

**Comment by mobile-ads-github** [comment]
На вашем примере тоже не воспроизводится ни под симулятор ни под девайс. 
Можно ещё попробовать посмотреть на ваш сгенерированный iOS проект

**Comment by dethroneofall** [comment]
> На вашем примере тоже не воспроизводится ни под симулятор ни под девайс. Можно ещё попробовать посмотреть на ваш сгенерированный iOS проект

Что Вам скинуть всю сгенерированную папку или какие то отдельные файлы ?

**Comment by mobile-ads-github** [comment]
Всю папку

**Comment by mobile-ads-github** [comment]
Собрал и этот проект без проблем. По настройке проекта тоже все ок.
А каким Xсode вы пользуетесь ?

**Comment by dethroneofall** [comment]
> Попробуйте использовать 14+

Хорошо, сейчас обновлю и отпишу

**Comment by dethroneofall** [comment]
> Попробуйте использовать 14+

Сбилдилось, спасибо большое )))
Добавьте пожалуйста, все же в туториале, что с такой то версии нужна версия xcode такая то, чтобы потом у таких как я не было вопросов, думаю это было бы уместно
