### ISSUE TITLE
В большинстве случаев не показывается реклама

### ISSUE THREAD

**Issue by Sergey-Mazlov** [yandexmobile/yandex-ads-unity-plugin#60]
Следующий лог с работой скрипта **YandexMobileAdsRewardedAdDemoScript.cs**, реклама за вознаграждение не всегда отображается, лишь приходят событие Shown и Dismissed, хотя по факту реклама даже не открылась. Аналогичная проблема и для Interstitial рекламы.

2023.05.03 12:01:30.605 984 1051 Info Unity **Rewarded Ad is requested**
2023.05.03 12:01:30.605 984 1051 Info Unity YandexMobileAdsRewardedAdDemoScript:OnGUI()
2023.05.03 12:01:30.605 984 1051 Info Unity 
2023.05.03 12:01:31.932 984 1051 Info Unity **HandleRewardedAdLoaded event received**
2023.05.03 12:01:31.932 984 1051 Info Unity YandexMobileAds.Common.MainThreadDispatcher:Update()
2023.05.03 12:01:31.932 984 1051 Info Unity 
2023.05.03 12:01:36.987 984 984 Info ViewRootImpl@6f2f05c[UnityPlayerActivity] ViewPostIme pointer 0
2023.05.03 12:01:37.045 984 984 Info ViewRootImpl@6f2f05c[UnityPlayerActivity] ViewPostIme pointer 1
2023.05.03 12:01:37.164 984 984 Info ViewRootImpl@6f2f05c[UnityPlayerActivity] stopped(false) old = false
2023.05.03 12:01:37.172 984 984 Info ViewRootImpl@6f2f05c[UnityPlayerActivity] MSG_WINDOW_FOCUS_CHANGED 0 0
2023.05.03 12:01:37.185 984 984 Info ViewRootImpl@6f2f05c[UnityPlayerActivity] performTraversals params={(0,0)(fillxfill) sim={adjust=pan forwardNavigation} layoutInDisplayCutoutMode=shortEdges ty=BASE_APPLICATION fmt=TRANSLUCENT wanim=0x1030309
2023.05.03 12:01:37.185 984 984 Info ViewRootImpl@6f2f05c[UnityPlayerActivity]   fl=80810500
2023.05.03 12:01:37.185 984 984 Info ViewRootImpl@6f2f05c[UnityPlayerActivity]   pfl=12020040
2023.05.03 12:01:37.185 984 984 Info ViewRootImpl@6f2f05c[UnityPlayerActivity]   vsysui=1707
2023.05.03 12:01:37.185 984 984 Info ViewRootImpl@6f2f05c[UnityPlayerActivity]   apr=LOW_PROFILE_BARS
2023.05.03 12:01:37.185 984 984 Info ViewRootImpl@6f2f05c[UnityPlayerActivity]   bhv=SHOW_TRANSIENT_BARS_BY_SWIPE
2023.05.03 12:01:37.185 984 984 Info ViewRootImpl@6f2f05c[UnityPlayerActivity]   fitSides= naviIconColor=0}
2023.05.03 12:01:37.185 984 984 Info ViewRootImpl@6f2f05c[UnityPlayerActivity] performTraversals mFirst=false windowShouldResize=false viewVisibilityChanged=false mForceNextWindowRelayout=false params={(0,0)(fillxfill) sim={adjust=pan forwardNavigation} layoutInDisplayCutoutMode=shortEdges ty=BASE_APPLICATION fmt=TRANSLUCENT wanim=0x1030309
2023.05.03 12:01:37.185 984 984 Info ViewRootImpl@6f2f05c[UnityPlayerActivity]   fl=80810500
2023.05.03 12:01:37.185 984 984 Info ViewRootImpl@6f2f05c[UnityPlayerActivity]   pfl=12020040
2023.05.03 12:01:37.185 984 984 Info ViewRootImpl@6f2f05c[UnityPlayerActivity]   vsysui=1707
2023.05.03 12:01:37.185 984 984 Info ViewRootImpl@6f2f05c[UnityPlayerActivity]   apr=LOW_PROFILE_BARS
2023.05.03 12:01:37.185 984 984 Info ViewRootImpl@6f2f05c[UnityPlayerActivity]   bhv=SHOW_TRANSIENT_BARS_BY_SWIPE
2023.05.03 12:01:37.185 984 984 Info ViewRootImpl@6f2f05c[UnityPlayerActivity]   fitSides= naviIconColor=0}
2023.05.03 12:01:37.191 984 984 Info ViewRootImpl@6f2f05c[UnityPlayerActivity] updateBlastSurfaceIfNeeded mBlastBufferQueue=0xb4000070bc4aec10 isSameSurfaceControl=true
2023.05.03 12:01:37.191 984 984 Info ViewRootImpl@6f2f05c[UnityPlayerActivity] Relayout returned: old=(0,0,2316,1080) new=(0,0,2316,1080) req=(2316,1080)0 dur=6 res=0x0 s={true 0xb40000714c4b5ae0} ch=false seqId=0
2023.05.03 12:01:37.191 984 984 Info ViewRootImpl@6f2f05c[UnityPlayerActivity] updateBoundsLayer: t = android.view.SurfaceControl$Transaction@d30de21 sc = Surface(name=Bounds for - com.MazlovProduction.SlipperySlope/com.unity3d.player.UnityPlayerActivity@0)/@0x2d246 frame = 12
2023.05.03 12:01:37.191 984 984 Info ViewRootImpl@6f2f05c[UnityPlayerActivity] mWNT: t=0xb40000707c4a7010 mBlastBufferQueue=0xb4000070bc4aec10 fn= 12 caller= android.view.ViewRootImpl.prepareSurfaces:2985 android.view.ViewRootImpl.performTraversals:4233 android.view.ViewRootImpl.doTraversal:3116 
2023.05.03 12:01:37.191 984 984 Verbose ViewRootImpl@6f2f05c[UnityPlayerActivity] Surface Surface(name=null)/@0x2a3f8cb drawing to bitmap w=2316, h=1080
2023.05.03 12:01:37.192 984 984 Info ViewRootImpl@6f2f05c[UnityPlayerActivity] Drawing: package:com.MazlovProduction.SlipperySlope, metrics=DisplayMetrics{density=2.8125, width=2106, height=1080, scaledDensity=2.8125, xdpi=375.78073, ydpi=374.69025}, compatibilityInfo={450dpi always-compat}
2023.05.03 12:01:37.201 984 984 Info ViewRootImpl@6f2f05c[UnityPlayerActivity] MSG_WINDOW_FOCUS_CHANGED 1 0
2023.05.03 **12:01:37.222** 984 1051 Info Unity **HandleRewardedAdShown event received**
2023.05.03 12:01:37.222 984 1051 Info Unity YandexMobileAds.Common.MainThreadDispatcher:Update()
2023.05.03 12:01:37.222 984 1051 Info Unity 
2023.05.03 **12:01:37.223** 984 1051 Info Unity **HandleRewardedAdDismissed event received**
2023.05.03 12:01:37.223 984 1051 Info Unity YandexMobileAds.Common.MainThreadDispatcher:Update()
2023.05.03 12:01:37.223 984 1051 Info Unity

**Comment by Sergey-Mazlov** [comment]
В случае с YandexMobileAdsInterstitialDemoScript.cs, реклама не отображается от слова совсем:

2023.05.03 12:25:56.343 7109 7211 Warn Unity Interstitial is requested
2023.05.03 12:25:56.343 7109 7211 Warn Unity YandexMobileAdsInterstitialDemoScript:OnGUI()
2023.05.03 12:25:56.343 7109 7211 Warn Unity 
2023.05.03 12:25:56.833 7109 7211 Warn Unity HandleInterstitialLoaded event received
2023.05.03 12:25:56.833 7109 7211 Warn Unity YandexMobileAds.Common.MainThreadDispatcher:Update()
2023.05.03 12:25:56.833 7109 7211 Warn Unity 
2023.05.03 12:25:58.389 7109 7109 Info ViewRootImpl@5d53216[UnityPlayerActivity] ViewPostIme pointer 0
2023.05.03 12:25:58.481 7109 7109 Info ViewRootImpl@5d53216[UnityPlayerActivity] ViewPostIme pointer 1
2023.05.03 12:25:58.592 7109 7109 Info ViewRootImpl@5d53216[UnityPlayerActivity] stopped(false) old = false
2023.05.03 12:25:58.599 7109 7109 Info ViewRootImpl@5d53216[UnityPlayerActivity] MSG_WINDOW_FOCUS_CHANGED 0 0
2023.05.03 12:25:58.604 7109 7109 Info ViewRootImpl@5d53216[UnityPlayerActivity] performTraversals params={(0,0)(fillxfill) sim={adjust=pan forwardNavigation} layoutInDisplayCutoutMode=shortEdges ty=BASE_APPLICATION fmt=TRANSLUCENT wanim=0x1030309 sysuil=true
2023.05.03 12:25:58.604 7109 7109 Info ViewRootImpl@5d53216[UnityPlayerActivity]   fl=80810500
2023.05.03 12:25:58.604 7109 7109 Info ViewRootImpl@5d53216[UnityPlayerActivity]   pfl=12020040
2023.05.03 12:25:58.604 7109 7109 Info ViewRootImpl@5d53216[UnityPlayerActivity]   vsysui=1707
2023.05.03 12:25:58.604 7109 7109 Info ViewRootImpl@5d53216[UnityPlayerActivity]   apr=LOW_PROFILE_BARS
2023.05.03 12:25:58.604 7109 7109 Info ViewRootImpl@5d53216[UnityPlayerActivity]   bhv=SHOW_TRANSIENT_BARS_BY_SWIPE
2023.05.03 12:25:58.604 7109 7109 Info ViewRootImpl@5d53216[UnityPlayerActivity]   fitSides= naviIconColor=0}
2023.05.03 12:25:58.604 7109 7109 Info ViewRootImpl@5d53216[UnityPlayerActivity] performTraversals mFirst=false windowShouldResize=false viewVisibilityChanged=false mForceNextWindowRelayout=false params={(0,0)(fillxfill) sim={adjust=pan forwardNavigation} layoutInDisplayCutoutMode=shortEdges ty=BASE_APPLICATION fmt=TRANSLUCENT wanim=0x1030309 sysuil=true
2023.05.03 12:25:58.604 7109 7109 Info ViewRootImpl@5d53216[UnityPlayerActivity]   fl=80810500
2023.05.03 12:25:58.604 7109 7109 Info ViewRootImpl@5d53216[UnityPlayerActivity]   pfl=12020040
2023.05.03 12:25:58.604 7109 7109 Info ViewRootImpl@5d53216[UnityPlayerActivity]   vsysui=1707
2023.05.03 12:25:58.604 7109 7109 Info ViewRootImpl@5d53216[UnityPlayerActivity]   apr=LOW_PROFILE_BARS
2023.05.03 12:25:58.604 7109 7109 Info ViewRootImpl@5d53216[UnityPlayerActivity]   bhv=SHOW_TRANSIENT_BARS_BY_SWIPE
2023.05.03 12:25:58.604 7109 7109 Info ViewRootImpl@5d53216[UnityPlayerActivity]   fitSides= naviIconColor=0}
2023.05.03 12:25:58.608 7109 7109 Info ViewRootImpl@5d53216[UnityPlayerActivity] updateBlastSurfaceIfNeeded mBlastBufferQueue=0xb4000070bc5b8c50 isSameSurfaceControl=true
2023.05.03 12:25:58.608 7109 7109 Info ViewRootImpl@5d53216[UnityPlayerActivity] Relayout returned: old=(0,0,2316,1080) new=(0,0,2316,1080) req=(2316,1080)0 dur=4 res=0x0 s={true 0xb40000714c4b5ae0} ch=false seqId=0
2023.05.03 12:25:58.608 7109 7109 Info ViewRootImpl@5d53216[UnityPlayerActivity] updateBoundsLayer: t = android.view.SurfaceControl$Transaction@ee4e88b sc = Surface(name=Bounds for - com.MazlovProduction.SlipperySlope/com.unity3d.player.UnityPlayerActivity@1)/@0xd6518e1 frame = 5
2023.05.03 12:25:58.608 7109 7109 Info ViewRootImpl@5d53216[UnityPlayerActivity] mWNT: t=0xb40000707c4a6a70 mBlastBufferQueue=0xb4000070bc5b8c50 fn= 5 caller= android.view.ViewRootImpl.prepareSurfaces:2985 android.view.ViewRootImpl.performTraversals:4233 android.view.ViewRootImpl.doTraversal:3116 
2023.05.03 12:25:58.609 7109 7109 Verbose ViewRootImpl@5d53216[UnityPlayerActivity] Surface Surface(name=null)/@0x9d14d9 drawing to bitmap w=2316, h=1080
2023.05.03 12:25:58.610 7109 7109 Info ViewRootImpl@5d53216[UnityPlayerActivity] Drawing: package:com.MazlovProduction.SlipperySlope, metrics=DisplayMetrics{density=2.8125, width=2106, height=1080, scaledDensity=2.8125, xdpi=375.78073, ydpi=374.69025}, compatibilityInfo={450dpi always-compat}
2023.05.03 12:25:58.617 7109 7109 Info ViewRootImpl@5d53216[UnityPlayerActivity] MSG_WINDOW_FOCUS_CHANGED 1 0
2023.05.03 12:25:58.625 7109 7211 Warn Unity HandleInterstitialShown event received
2023.05.03 12:25:58.625 7109 7211 Warn Unity YandexMobileAds.Common.MainThreadDispatcher:Update()
2023.05.03 12:25:58.625 7109 7211 Warn Unity 
2023.05.03 12:25:58.668 7109 7211 Warn Unity HandleInterstitialDismissed event received
2023.05.03 12:25:58.668 7109 7211 Warn Unity YandexMobileAds.Common.MainThreadDispatcher:Update()
2023.05.03 12:25:58.668 7109 7211 Warn Unity

**Comment by mobile-ads-github** [comment]
Здраствуйте. Проблему воспроизвести не получилось. 
Для дальнейшего разбора нужно больше информации. Укажите пожалуйста платформу и версию плагина.

**Comment by Sergey-Mazlov** [comment]
Платформа android. Версия плагина 2.7.0

**Comment by Sergey-Mazlov** [comment]
Эх, классная у вас поддержка получается...

**Comment by Gy9vin** [comment]
> Эх, классная у вас поддержка получается...

У тебя получилось решить проблему? столкнулся с такой же уже всю голову сломал!

**Comment by AppMetricaSupport** [comment]
Добрый день!Ваше письмо получено и зарегистрировано под уникальным номером № 24578053. Ответ обязательно будет предоставлен, пожалуйста, ожидайте.Просим Вас не отправлять повторное письмо по данному вопросу - оно будет считаться новой заявкой и может быть обработано позднее.Помощь сервиса: https://yandex.ru/support/direct/?from=email--С уважением,Отдел клиентского сервисател.: 8 800 234-24-80 (звонок из регионов России бесплатный)тел.: +7 495 739-37-77&nbsp15.06.2023, 08:24, "Mikhail" ***@***.***>:

Эх, классная у вас поддержка получается...

У тебя получилось решить проблему? столкнулся с такой же уже всю голову сломал!

**Comment by strategimws** [comment]
Такая же проблема
В версии 2.3.0 при показе межстраничной рекламы, данная ситуация не воспроизводится.
Во всех поздних версиях, ситация такая же, как в постах выше.
Писал в поддержку, одни только отговорки, что типа у них ничего не воспроизводится. Складывается ощущение, что им просто пофиг. Наверное так оно и есть.
Проще тогда уж использовать Admob + Unity Ads, реально меньший геморой.

**Comment by strategimws** [comment]
> Здраствуйте. Проблему воспроизвести не получилось. Для дальнейшего разбора нужно больше информации. Укажите пожалуйста платформу и версию плагина.

Так вы проверяйте не на тестовых блоках а на реальных (за которые капают деньги). 
Тестовые блоки, как раз таки отображаются идеально, и на них действительно не воспроизводится. После прохождения модерации приложения, уже Rewarded и Interstitial нихрена не отображаются.

**Comment by mobile-ads-github** [comment]
Здравствуйте! 
Приносим извинения за поздний ответ.

Решить эту проблему показа рекламы можно несколькими способами:

1. Включить кастомные template's для генерируемого проекта. Для этого в настройках сборки плеера (Build Settings -> Player Settings -> Publishing Settings -> Build) нужно поставить галочку Custom Main Gradle Template.
2. Собирать проект с помощью Android Studio. Для этого в настройках сборки нужно поставить галочку Export Project.
3. Добавить флаг android.enableDexingArtifactTransform=false в gradleTemplate.properties.
