### ISSUE TITLE
Креш на запуске Android | апметрика

### ISSUE THREAD

**Issue by dimmduh** [yandexmobile/yandex-ads-unity-plugin#61]
ActivityThread Failed to find provider info for com.yandex.preinstallsatellite.appmetrica.provider

Версия Release 2.7.0 lite
В проекте уже имеется com.yandex.android:mobmetricalib:5.2.0

**Comment by mobile-ads-github** [comment]
Здравствуйте! Тут проблема с [AppMetrica](https://yandex.ru/dev/appmetrica/), обратитесь, пожалуйста, к ним.
