### ISSUE TITLE
Ошибка при открытии Yandex-mobileads-lite-2.7.0.unitypackage

### ISSUE THREAD

**Issue by Maskusa** [yandexmobile/yandex-ads-unity-plugin#62]
Невозможно добавить пакет yandex-mobileads-lite-2.7.0.unitypackage
Версия 2.6.0 открывается нормально.

Демонстрация https://www.youtube.com/watch?v=355q7bHZdhc

Failed to import package with error: Couldn't decompress package.
Unity 2022.2.17 / 2020.3.48

**Comment by mobile-ads-github** [comment]
Здравствуйте! 
Приносим извинения за поздний ответ.

Мы не смогли у себя воспроизвести эту проблему. Если вопрос еще актуален, попробуйте импортировать последнюю версию [2.9.0](https://github.com/yandexmobile/yandex-ads-unity-plugin/tree/master/mobileads-unity-plugin).
