### ISSUE TITLE
[Banner rendering failed with timeout] Ошибка при загрузке баннера

### ISSUE THREAD

**Issue by steam3d** [yandexmobile/yandex-ads-unity-plugin#63]
Повторил быстрый старт с баннером:
https://yandex.ru/dev/mobile-ads/doc/plugins/unity/quick-start/banner.html

Плагин:
[yandex-mobileads-lite-2.7.0.unitypackage](https://github.com/yandexmobile/yandex-ads-unity-plugin/blob/master/mobileads-unity-plugin/yandex-mobileads-lite-2.7.0.unitypackage)

Версию Unity:
2021.3.22f1 LTS

Лог:
2023.05.20 21:58:42.454 19122 19244 Info Unity HandleAdFailedToLoad event received with message: Banner rendering failed with timeout
2023.05.20 21:58:42.454 19122 19244 Info Unity Assets.Scripts.YandexMobileAds:HandleAdFailedToLoad (object,YandexMobileAds.Base.AdFailureEventArgs) (at C:/Gitlab/justtype/Assets/Scripts/YandexMobileAds.cs:68)
2023.05.20 21:58:42.454 19122 19244 Info Unity YandexMobileAds.Banner/<>c__DisplayClass25_1:<ConfigureBannerEvents>b__7 () (at C:/Gitlab/justtype/Assets/YandexMobileAds/Banner.cs:123)
2023.05.20 21:58:42.454 19122 19244 Info Unity YandexMobileAds.Common.MainThreadDispatcher:Update () (at C:/Gitlab/justtype/Assets/YandexMobileAds/Common/MainThreadDispatcher.cs:63)

Пробовал на разных устройствах. Всегда одна и так же ошибка.

**Comment by mobile-ads-github** [comment]
Здравствуйте, был баг с демо-блоком demo-banner-yandex. Cейчас для flexible/inline уже исправили, можете проверить.
Если хотите использовать sticky, то планируем починить на этой неделе.
