### ISSUE TITLE
Unity IAP  перестает работать после того, как импортирую пакет YandexMobileAds 

### ISSUE THREAD

**Issue by IskanderNazarov** [yandexmobile/yandex-ads-unity-plugin#64]
Работаю на Unity 2021.3.3.
Импортировал YandexMobileAds - юнитивская система IAP перестала работать на iOS. Ну то есть не инициализируется, не грузит продукты. Когда удаляю плагин полностью из проекта, то все начинает работать нормально.

В Xcode пишет вот эту ошибку и больше ничего существенного.

**ProductName[6463:2287920] UnityIAP: SKProductRequest::didFailWithError: 0, Error Domain=SKErrorDomain Code=0 "Произошла неизвестная ошибка" UserInfo={NSLocalizedDescription=Произошла неизвестная ошибка, NSUnderlyingError=0x2810e7330 {Error Domain=ASDErrorDomain Code=950 "Unhandled exception" UserInfo={NSLocalizedDescription=Unhandled exception, NSLocalizedFailureReason=An unknown error occurred}}}. Unity Purchasing will retry in 60 seconds**

Запускаю на  iPad 7, IOS 16.3.1

**Comment by mobile-ads-github** [comment]
Здравствуйте, спасибо за Ваш репорт. Уточните пожалуйста, какую версию Yandex Mobile Ads - Unity плагина используете и какую версию iOS SDK? Проблема только на iOS?

**Comment by IskanderNazarov** [comment]
Вот эту, последнюю
<img width="596" alt="Screenshot 2023-05-24 at 09 43 44" src="https://github.com/yandexmobile/yandex-ads-unity-plugin/assets/28686116/0d6d1b2c-2de8-46fd-9623-981b52fb423a">

**Comment by mobile-ads-github** [comment]
В приведенных логах нет указания на наш SDK и в принципе нет деталей ошибки. С этими исходными данными к сожалению будет сложно понять причину. 
Возможно проблема на стороне настроек проекта. Как вариант - попробуйте воспроизвести на пустом проекте с IAP и Yandex Mobile Ads плагином

**Comment by mobile-ads-github** [comment]
This issue has been closed due to a lack of recent activity. If the problem is still relevant, please feel free to reopen the issue or comment with additional details. Thank you!

**Comment by IskanderNazarov** [comment]
> В приведенных логах нет указания на наш SDK и в принципе нет деталей ошибки. С этими исходными данными к сожалению будет сложно понять причину. Возможно проблема на стороне настроек проекта. Как вариант - попробуйте воспроизвести на пустом проекте с IAP и Yandex Mobile Ads плагином

Оказалось, Yandex Mobile Ads и Facebook не дружат. То есть я устатовил YMA в проект, где был фейсбук. Когда они вместе в проекте - покупки не работают. Как только удаляю из проекста либо YAM, либо FacebookSDK - все начинает нормально работать
