### ISSUE TITLE
NullReferenceException: YandexMobileAds.RewardedAd

### ISSUE THREAD

**Issue by dreamcodestudio** [yandexmobile/yandex-ads-unity-plugin#65]
- Unity editor version: 2020.3.34f1
- SDK version: 2.7.0
- Problematic Component: RewardedAd
- Target platform: Android
- Scripting Runtime: IL2CPP

Issue log:
`
YandexMobileAds.RewardedAd+<>c__DisplayClass38_5.<ConfigureRewardedAdEvents>b__15 () (at <00000000000000000000000000000000>:0)
System.Action.Invoke () (at <00000000000000000000000000000000>:0)
YandexMobileAds.Common.MainThreadDispatcher.Update () (at <00000000000000000000000000000000>:0)
`

**Comment by dreamcodestudio** [comment]
Более подробного stack trace нет, т.к регистрируется только на уровне Unity Reports
ошибок довольно мало, 1-2 в день и основные девайсы это
![image](https://github.com/yandexmobile/yandex-ads-unity-plugin/assets/7010398/11cc0d8c-b46d-47ed-b3ce-accd4752eda6)

**Comment by dreamcodestudio** [comment]
ошибок мало, но ситуация на актуальной версии sdk не изменилась в Unity `Crash and Exception Reporting`
![image](https://github.com/yandexmobile/yandex-ads-unity-plugin/assets/7010398/2480b47b-db43-4c23-a526-97d1bdd5b922)

**Comment by mobile-ads-github** [comment]
Добрый день! Вижу NullReferenceException. Можно добавить проверку на null в месте использования переменной.

**Comment by dreamcodestudio** [comment]
проблема не в вызывающем коде, а на уровне обертки `RewardedAd.cs`
![image](https://github.com/yandexmobile/yandex-ads-unity-plugin/assets/7010398/64714a0c-01ae-42ad-b981-0feee675bb6a)

т.к проверка на null происходит до смены контекста и это не гарантирует, что при вызове из главного потока Unity event `OnRewarded` не будет null

**Comment by dreamcodestudio** [comment]
например в `GoogleMobileAds` при аналогичном вызове, происходит проверка как раз уже в основном потоке Unity, на callback
`RaiseAction`
![image](https://github.com/yandexmobile/yandex-ads-unity-plugin/assets/7010398/a396259b-547e-4cbd-b850-133118fb980e)

**Comment by mobile-ads-github** [comment]
Спасибо за уточнение. Сейчас изучим вопрос и в ближайшее время дадим обратную связь.

**Comment by mobile-ads-github** [comment]
Добрый день! Возвращаемся с обратной связью. Приняли Exception в работу. За обновлениями можете следить на сайте https://yandex.ru/adv/news?tag=рекламная%20сеть.

**Comment by mobile-ads-github** [comment]
Здравствуйте! Проблема была исправлена в версии [6.0.0](https://github.com/yandexmobile/yandex-ads-unity-plugin/releases/tag/6.0.0)
