### ISSUE TITLE
Проблема с позиционированием AdPosition.BottomCenter в iOS

### ISSUE THREAD

**Issue by merrynose** [yandexmobile/yandex-ads-unity-plugin#66]
Добрый день!

Использую такой код для отображения баннера внизу экрана:
`banner = new Banner(adUnitId, bannerMaxSize, AdPosition.BottomCenter);`

Однако баннер отображается не внизу экрана, а внизу SafeArea (см. скрин), в результате чего баннер съезжает вверх, а внизу остается пустое место. Как это победить?

![photo_2023-06-07_23-27-30](https://github.com/yandexmobile/yandex-ads-unity-plugin/assets/73421658/3bcb5875-8989-47c7-a510-42f9e9722d8f)

**Comment by mobile-ads-github** [comment]
Добрый день! К сожалению, на данный момент такая функциональность не предусмотрена для unity плагина.
