### ISSUE TITLE
Ошибка Multiple commands produce при попытке билда под iOS

### ISSUE THREAD

**Issue by breakmt** [yandexmobile/yandex-ads-unity-plugin#68]
Добрый день! Пытаюсь сбилдить игру под iOS с Яндекс Медиацией (подключены My Target, MIntegral, Unity Ads, Pangle), но в Xcode получаю ошибку
```
error: Multiple commands produce '/Users/breakmt/Library/Developer/Xcode/DerivedData/Unity-iPhone-ekuqvmdrgpfnjuaoesiltcaasaqw/Build/Products/ReleaseForRunning-iphoneos/ToxicCityLab.app/YandexMobileAdsBundle.bundle'
    note: Target 'Unity-iPhone' (project 'Unity-iPhone') has copy command from '/Users/breakmt/Documents/GitHub/toxic/Build/Pods/YandexMobileAds/static/YandexMobileAds.xcframework/YandexMobileAdsBundle.bundle' to '/Users/breakmt/Library/Developer/Xcode/DerivedData/Unity-iPhone-ekuqvmdrgpfnjuaoesiltcaasaqw/Build/Products/ReleaseForRunning-iphoneos/ToxicCityLab.app/YandexMobileAdsBundle.bundle'
    note: That command depends on command in Target 'Unity-iPhone' (project 'Unity-iPhone'): script phase “[CP] Copy Pods Resources”
```
Порыл в интернете - пишут с похожей ошибкой удалить дубликат в Copy Bundle Resources в Buld Phases. Но там нет дубликатов.
<img width="827" alt="Снимок экрана 2023-07-03 в 19 16 52" src="https://github.com/yandexmobile/yandex-ads-unity-plugin/assets/1552169/18ebf151-486a-4381-b08d-8569d9cf5ccc">

Посоветуйте пожалуйста, что можно сделать?

Версия плагина последняя
Unity 2021.3.22f
Xcode 14.2

**Comment by AppMetricaSupport** [comment]
Добрый день!Ваше письмо получено и зарегистрировано под уникальным номером № 25000328. Ответ обязательно будет предоставлен, пожалуйста, ожидайте.Просим Вас не отправлять повторное письмо по данному вопросу - оно будет считаться новой заявкой и может быть обработано позднее.Помощь сервиса: https://yandex.ru/support/direct/?from=email--С уважением,Отдел клиентского сервисател.: 8 800 234-24-80 (звонок из регионов России бесплатный)тел.: +7 495 739-37-77&nbsp03.07.2023, 19:19, "breakmt" ***@***.***>:
Добрый день! Пытаюсь сбилдить игру под iOS с Яндекс Медиацией (подключены My Target, MIntegral, Unity Ads, Pangle), но в Xcode получаю ошибку
error: Multiple commands produce '/Users/breakmt/Library/Developer/Xcode/DerivedData/Unity-iPhone-ekuqvmdrgpfnjuaoesiltcaasaqw/Build/Products/ReleaseForRunning-iphoneos/ToxicCityLab.app/YandexMobileAdsBundle.bundle'
    note: Target 'Unity-iPhone' (project 'Unity-iPhone') has copy command from '/Users/breakmt/Documents/GitHub/toxic/Build/Pods/YandexMobileAds/static/YandexMobileAds.xcframework/YandexMobileAdsBundle.bundle' to '/Users/breakmt/Library/Developer/Xcode/DerivedData/Unity-iPhone-ekuqvmdrgpfnjuaoesiltcaasaqw/Build/Products/ReleaseForRunning-iphoneos/ToxicCityLab.app/YandexMobileAdsBundle.bundle'
    note: That command depends on command in Target 'Unity-iPhone' (project 'Unity-iPhone'): script phase “[CP] Copy Pods Resources”

Порыл в интернете - пишут с похожей ошибкой удалить дубликат в Copy Bundle Resources в Buld Phases. Но там нет дубликатов.

Посоветуйте пожалуйста, что можно сделать?
Версия плагина последняя
Unity 2021.3.22f
Xcode 14.2

**Comment by CheeryLee** [comment]
Дубликат на самом деле есть, и он как раз на скрине. Бандл с рекламой копируется на стадии _[CP] Copy Pods Resources_, поэтому его не нужно явно указывать в _Copy Bundle Resources_.
В классе `PostprocessBuildPlayerYandexMobileAds` есть ошибка. Удалите эту часть кода:

![image](https://github.com/yandexmobile/yandex-ads-unity-plugin/assets/11297752/37aee66e-0af1-40d3-8610-aaa222fcefab)

**Comment by breakmt** [comment]
Понятно, спасибо за ответ! Судя по количеству проблем и активности поддержки - пользоваться этим пока не стоит.

**Comment by mobile-ads-github** [comment]
Здравствуйте! 
Приносим извинения за поздний ответ.

С версии плагина 2.8.0 `YandexMobileAdsBundle.bundle` добавляется в iOS проект автоматически с помощью `PostprocessBuildPlayerYandexMobileAds.cs`. Поэтому если вы добавляли `YandexMobileAdsBundle.bundle` вручную теперь этого делать не нужно.

**Comment by dreamcodestudio** [comment]
текущий PostBuild будет нормально работать только на xcodeproj, но если собирать проект через xcworkspace c Pods будет возникать 
`error: Multiple commands produce`

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-2230. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-2230 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by mobile-ads-github** [comment]
Здравствуйте! Советуем сначала удалить все pod-зависимости, затем заново установить через pod install. В таком случае дублирование зависимостей будет  точно устранено.

**Comment by dreamcodestudio** [comment]
> Здравствуйте! Советуем сначала удалить все pod-зависимости, затем заново установить через pod install. В таком случае дублирование зависимостей будет точно устранено.

Через `External Dependency Manager` это делается автоматически, проблема именно в вашем `Postprocess`, для проектов с `iOSResolver` он не нужен, это дублирует логику resolvera

**Comment by mobile-ads-github** [comment]
Благодарим за обращение, обнаружили проблему на нашей стороне.
Исправление будет доступно в ближайшем релизе.

**Comment by mobile-ads-github** [comment]
Здравствуйте! Проблема была исправлена в версии [6.0.0](https://github.com/yandexmobile/yandex-ads-unity-plugin/releases/tag/6.0.0)
