### ISSUE TITLE
Краш при непрогрузке интерстишиала в медиации с IronSource

### ISSUE THREAD

**Issue by Voley** [yandexmobile/yandex-ads-unity-plugin#70]
На слабом интернете при загрузке интерстишиала при попытке его показа падает. Как я понял не хватает метода onAdLoadFailed в адаптере.

<img width="721" alt="image" src="https://github.com/yandexmobile/yandex-ads-unity-plugin/assets/705508/956b4f99-5294-4e99-b956-07b5a642971d">

(текстовая версия приложена к ниже)
`

Как воспроизвел - на медленном интернете запросил интерстишиал и попросил показать, падение.
Интеграция через IronSource.

Код вызова - 
<img width="472" alt="image" src="https://github.com/yandexmobile/yandex-ads-unity-plugin/assets/705508/da97d78c-1e68-4be8-807b-f4ace1fa83d0">

Версия адаптера яндекса 
com.yandex.android:mobileads:5.9.0
ironsource-mobileads-mediation-2.8.0
yandex-mobileads-lite-2.8.0
ironsource sdk 7.3.1.1

Версия Юнити LTS 2022.3.2f1

Девайс - <img width="307" alt="image" src="https://github.com/yandexmobile/yandex-ads-unity-plugin/assets/705508/5f538861-3600-485b-96e5-0b4c9e795ec3">

Полный лог - 
[log.zip](https://github.com/yandexmobile/yandex-ads-unity-plugin/files/12113156/log.zip)

Второй лог - 
[log2.zip](https://github.com/yandexmobile/yandex-ads-unity-plugin/files/12113285/log2.zip)

**Comment by Voley** [comment]
В проде тоже начало наваливать этих крешей, вот стек трейс

<img width="1034" alt="image" src="https://github.com/yandexmobile/yandex-ads-unity-plugin/assets/705508/5878823f-d9bc-4bc9-8cd1-88573dfa0049">

**Comment by mobile-ads-github** [comment]
Здравствуйте! 
Приносим извинения за поздний ответ.

По всей видимости краш вызван ошибкой в IronSource mediation SDK версии 7.3.1.

Пакет [ironsource-mobileads-mediation-2.8.0.unitypackage](https://github.com/yandexmobile/yandex-ads-unity-plugin/blob/master/third-party-networks-mediation/ironsource/ironsource-mobileads-mediation-2.8.0.unitypackage) был собран c нативной версией адаптера IronSource 5.9.0 в совместимости с IronSource SDK версии 7.3.1. 

В настоящее время мы работаем над следующим релизом плагина, который будет поддерживать работу с IronSourceSDK 7.3.1.1.

В качестве быстрого решения, вы можете самостоятельно поднять версию нативного Android SDK до версии `5.10.0` и адаптера для IronSource до версии `5.10.0.0` в файле
`ProjectRoot/YandexMobileAds/Editor/IronSourceMobileadsMediationDependencies.xml`

```xml
<dependencies>
    <androidPackages>
        <androidPackage spec="com.yandex.android:mobileads:5.10.0">
            <repositories>
                <repository>https://maven.google.com/</repository>
            </repositories>
        </androidPackage>
        <androidPackage spec="com.yandex.ads.adapter:ironsource-mobileads:5.10.0.0">
            <repositories>
                <repository>https://maven.google.com/</repository>
            </repositories>
        </androidPackage>
    </androidPackages>
    <!-- ... -->
</dependencies>
```

**Comment by mobile-ads-github** [comment]
This issue has been closed due to a lack of recent activity. If the problem is still relevant, please feel free to reopen the issue or comment with additional details. Thank you!
