### ISSUE TITLE
2.8.0 and 2.9.0 plugin version wont show interstitial ad, when building apk directly from Unity

### ISSUE THREAD

**Issue by ivana-pejic** [yandexmobile/yandex-ads-unity-plugin#72]
When using those plugin versions with Unity blank project and sample interstitial script after Load interstital event, clicking on button "Show interstital" does not showing any sample ad at all. All it does is raising event InterstialShowed and after that immediately event InterstitialDismissed with no interstitial being showed.

**Comment by mobile-ads-github** [comment]
Hello!
Thank you for the report!

Please check if the `Custom Main Gradle Template` setting is enabled in the `Build Settings -> Player Settings -> Publishing Settings -> Build`.

<img width="954" alt="image" src="https://github.com/yandexmobile/yandex-ads-unity-plugin/assets/31896236/b0167432-1532-4a88-9d4d-204507004fd7">


If it's disabled, enabled it and trigger the force resolution of the dependencies using `Assets -> External Dependency Manager -> Android Resolver -> Force Resolve`
