### ISSUE TITLE
Samples YandexMobileAdsBannerDemoScript

### ISSUE THREAD

**Issue by RickSaint577** [yandexmobile/yandex-ads-unity-plugin#75]
this.banner = new Banner(adUnitId, bannerMaxSize, AdPosition.BottomCenter); not working
this.banner = new Banner(adUnitId, bannerSize, AdPosition.BottomCenter); THIS WORK

**Comment by mobile-ads-github** [comment]
Thank you for your report!

Fix has been merged into master branch.
