### ISSUE TITLE
feat: Asset package > Unity package registry

### ISSUE THREAD

**Issue by dreamcodestudio** [yandexmobile/yandex-ads-unity-plugin#78]
Здравствуйте, в современных проектах на Unity уже довольно часто используются [Unity Packages](https://docs.unity3d.com/Manual/upm-ui-install.html), в результате перехода на `asmdef` workflow, хотелось бы уточнить нет ли этого в планах на будущие релизы (речь в первую очередь о Common домены, без учета сторонних медиаций) ?
Т.к заметно упрощает процесс обновления сторонних SDK разработчикам, потому что они находятся в изолированной области и нет нужды в создании ручных компоновок asmdef для Ads API функционала.
Плюс это сильно упрощает управления ассетами и нативным библиотеками (удаление, обновления, импорта), избавляет от случая существования `deprecated` версий при обновлении SDK и конфликта версий.

Сейчас существует довольно много механизмов размещения:

- OpenUPM
- NPM
- Self Hosted proxy registry

#
Cейчас source лежит в виде  `.unitypackage`,  поэтому довольно сложно следить за изменениями которые происходят на уровне Unity Wrapper или например делать форки репозитория.

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-2400. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-2400 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by mobile-ads-github** [comment]
Здравствуйте! Спасибо за предложение. У нас есть в планах добавить поддержку установки SDK через Package Manager, но точных сроков пока назвать не могу.
