### ISSUE TITLE
Exception: Field currentActivity or type signature  not found

### ISSUE THREAD

**Issue by OverF1Ow** [yandexmobile/yandex-ads-unity-plugin#79]
Здравствуйте. Обновил sdk до 6.0.1 и теперь в эдиторе юнити лезет ошибка:

Exception: Field currentActivity or type signature  not found
UnityEngine._AndroidJNIHelper.GetFieldID (System.IntPtr jclass, System.String fieldName, System.String signature, System.Boolean isStatic) (at <4b2cb8eb73474a2a8fca972ae0c77937>:0)
UnityEngine.AndroidJNIHelper.GetFieldID (System.IntPtr javaClass, System.String fieldName, System.String signature, System.Boolean isStatic) (at <4b2cb8eb73474a2a8fca972ae0c77937>:0)
UnityEngine._AndroidJNIHelper.GetFieldID[ReturnType] (System.IntPtr jclass, System.String fieldName, System.Boolean isStatic) (at <4b2cb8eb73474a2a8fca972ae0c77937>:0)
UnityEngine.AndroidJNIHelper.GetFieldID[FieldType] (System.IntPtr jclass, System.String fieldName, System.Boolean isStatic) (at <4b2cb8eb73474a2a8fca972ae0c77937>:0)
UnityEngine.AndroidJavaObject._GetStatic[FieldType] (System.String fieldName) (at <4b2cb8eb73474a2a8fca972ae0c77937>:0)
UnityEngine.AndroidJavaObject.GetStatic[FieldType] (System.String fieldName) (at <4b2cb8eb73474a2a8fca972ae0c77937>:0)
YandexMobileAds.Platforms.Android.Utils.GetCurrentActivity () (at Assets/YandexMobileAds/Platforms/Android/Utils.cs:197)
YandexMobileAds.Platforms.Android.RewardedAdLoaderClient..ctor () (at Assets/YandexMobileAds/Platforms/Android/RewardedAdLoaderClient.cs:29)
YandexMobileAds.Platforms.YandexMobileAdsClientFactory.BuildRewardedAdLoaderClient () (at Assets/YandexMobileAds/Platforms/YandexMobileAdsClientFactory.cs:50)
YandexMobileAds.RewardedAdLoader..ctor () (at Assets/YandexMobileAds/RewardedAdLoader.cs:42)
StoreRewardedAdControl.Awake () (at Assets/Scripts/Ad/StoreRewardedAdControl.cs:19)

На андроид устройстве само собой такой ошибки нет.
Юнити 2022.3.10.

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-2484. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-2484 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by OverF1Ow** [comment]
Удалил sdk, поставил заново и ошибка исчезла.

**Comment by mobile-ads-github** [comment]
Отлично! Пишите, если ошибка появится вновь.
