### ISSUE TITLE
Didn't find class

### ISSUE THREAD

**Issue by nlaourayed** [yandexmobile/yandex-ads-unity-plugin#8]
i get this error :
`     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.yandex.mobile.ads.unity.wrapper.banner.UnityBannerListener" on path: DexPathList[[zip file "/data/app/com.DefaultCompany.tsts-1/base.apk"],nativeLibraryDirectories=[/data/app/com.DefaultCompany.tsts-1/lib/arm, /vendor/lib, /system/lib]]
`

**Comment by mobile-ads-github** [comment]
Здраствуйте! Спасибо за репорт. Используйте, пожалуйста [Google Resolver](https://github.com/googlesamples/unity-jar-resolver) со сборкой [yandex-mobileads-lite-2.0.0.unitypackage](https://github.com/yandexmobile/yandex-ads-unity-plugin/blob/master/mobileads-unity-plugin/yandex-mobileads-lite-2.0.0.unitypackage).
