### ISSUE TITLE
При показе рекламы зависает приложение

### ISSUE THREAD

**Issue by Sergey1296** [yandexmobile/yandex-ads-unity-plugin#82]
Обновил версию до 6.1.0 удалив все файлы старой версии. При выполнении функции показать ShowInterstitial игра может зависнуть, но иногда реклама загружается и показывает нормально. Использовал скрипты с папки samples, но и там тоже самое. То показывает то просто зависает приложение без отображении рекламы. Пробовал на двух устройствах Android.

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-2545. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-2545 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by mobile-ads-github** [comment]
Здравствуйте! Благодарим за обращение.

Включите в настройках сборки Android проекта опции "Custom Main Gradle Template" и "Custom Gradle Properties Template"

<img width="664" alt="image" src="https://github.com/yandexmobile/yandex-ads-unity-plugin/assets/31896236/d28faca2-2b7b-4162-9536-87a29ff73d13">

**Comment by mobile-ads-github** [comment]
> Версия Unity 2022.3.12f LTS, target sdk 33. Установив эти галочки возникли новые проблемы, ошибки при сборке. Почему это обновление не может работать с коробки?

Уточните пожалуйста, какие проблемы возникают при сборке?

**Comment by Sergey1296** [comment]
В общем с проблемами при сборке Custom Main Gradle Template разобрался, оказывается у последней версии Unity тоже есть некоторые проблемы при создании билда. До этого я ещё откатился до 2.9.0 плагина яндекса. Позже попробую вновь поставить 6.1.0 и отпишусь.

**Comment by Sergey1296** [comment]
В общем теперь с  "Custom Main Gradle Template" и "Custom Gradle Properties Template" (у которых я долго исправлял ошибки при билде), рекламу показывает хорошо на 6.1.0. Спасибо!
