### ISSUE TITLE
Последний рабочий выпуск содержит SDK с критическими ошибками

### ISSUE THREAD

**Issue by denis22718** [yandexmobile/yandex-ads-unity-plugin#83]
Обновил плагин медиации до новой версии (6.1.0) и через некоторое время после загрузки обновления в гугл плей вылезло вот такое сообщение: 
![2023-11-02_08-53-39](https://github.com/yandexmobile/yandex-ads-unity-plugin/assets/32695950/fecaa8e7-5d2e-444b-a005-b4c7aa7a9f0d)

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-2552. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-2552 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by mobile-ads-github** [comment]
Здравствуйте! Мы исправим это в следующем релизе
