### ISSUE TITLE
RewardedAd - реклама закрывается сразу после показа

### ISSUE THREAD

**Issue by Spectralon** [yandexmobile/yandex-ads-unity-plugin#84]
04.03.2023 я опубликовал Android-приложение, в котором используется плагин yandex-mobileads-lite-**2.6.0**. В приложение встроена реклама типа "Видео с вознаграждением" и "Баннер". После публикации на протяжении как минимум нескольких месяцев всё работало нормально.
В какой-то момент реклама типа "Видео с вознаграждением" перестала показываться (в том числе на клиентских устройствах). Баннерная реклама работает нормально.

Программа ведёт себя следующим образом:

<img src="https://github.com/yandexmobile/yandex-ads-unity-plugin/assets/68746803/984cd720-80af-4642-9e6c-d5b84fba4511" width="400">

1. Запрос рекламы (RequestRewardedAd)
2. Ивент RewardedAd.OnRewardedAdLoaded
3. Показ рекламы (RewardedAd.Show())
4. Ивент RewardedAd.OnRewardedAdShown
5. Ивент RewardedAd.OnRewardedAdDismissed

Пункты 1-4 - нормальное поведение программы. Пункт 5 - сейчас происходит всегда только таким образом, независимо от текущих условий работы программы.
С точки зрения пользователя реклама не появляется на экране вообще.

При обновлении плагина до версии **6.1.0** проблема сохраняется. Немного изменяется поведение программы:
1. После запроса на показ рекламы (п. 4) возникает следующий блок:
<img src="https://github.com/yandexmobile/yandex-ads-unity-plugin/assets/68746803/d179fcac-4bb3-49a6-ac42-9b0534f7a410" width="400">

2. Если нажать "Продолжить просмотр" - программа зависнет.
3. Если нажать "Отказаться от награды" - поведение как с версией 2.6.0.

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-2562. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-2562 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by mobile-ads-github** [comment]
Здравствуйте! Благодарим за обращение.

Включите в настройках сборки Android проекта опции "Custom Main Gradle Template" и "Custom Gradle Properties Template".

<img width="664" alt="image" src="https://github.com/yandexmobile/yandex-ads-unity-plugin/assets/31896236/d28faca2-2b7b-4162-9536-87a29ff73d13">

Затем, перед сборкой проекта, удалите скаченные зависимости (Assets -> External Dependency Manager -> Android Resolver -> Delete resolved libraries) и установите их снова (Assets -> External Dependency Manager -> Android Resolver -> Resolve )

**Comment by Spectralon** [comment]
Здравствуйте, спасибо за помощь!
Я обновил плагин до версии 6.1.0, включил опцию "Custom Main Gradle Template". При сборке проекта возникла следующая ошибка:

> Configuration `releaseRuntimeClasspath` contains AndroidX dependencies, but the `android.useAndroidX` property is not enabled, which may cause runtime issues.

Чтобы её исправить, пришлось дописать в gradle.properties следующие 2 строчки:

![image](https://github.com/yandexmobile/yandex-ads-unity-plugin/assets/68746803/7cfc7d14-5b85-4637-9b7e-bc4bc01a62b6)
`android.useAndroidX=true`
`android.enableJetifier=true`

После этого проект собрался нормально, сейчас **проблема решена**. 
Но мне всё ещё кажется странным, что ошибка возникла в том числе и в приложении, опубликованном ранее и работавшем нормально длительный срок времени (без обновлений!). Возможно, существует некая проблема с обратной совместимостью старых версий плагина?

**Comment by Sergey1296** [comment]
У меня тоже самое со старым плагином, тоже публиковал весной этого года, вроде версия 2.7.0 была. Тоже в последнее время перестала показываться реклама с вознаграждением а так же межстраничная.

**Comment by gilvrey** [comment]
У меня такая же проблема после обновления плагина на версию 6.0.0 (в 6.1.0 проблема сохраняется). Не работает показ RewardedAd, показывается такое же окно, как на скрине, после нажатия на кнопку "Продолжить просмотр" всё зависает. Такая же проблема есть и с межстраничной рекламой, когда отрабатывает показ такой рекламы, то сам баннер не показывается, появляются системные кнопки андроида и на этом всё зависает. При этом до обновления всё работало корректно.

**Comment by mobile-ads-github** [comment]
@Sergey1296 @gilvrey Здравствуйте! Благодарим за обращения!

Решение описанное выше должно помочь и в ваших случаях.

Источник проблемы - некорректный desugaring кода транзитивных зависимостей SDK. По всей видимости, это вызвано тем, что по умолчанию, ExternalDependencyManager подключает зависимости к gradle проекту просто как aar файлы, что в свою очередь нарушает стандартный механизм дешугаринга кода. При использовании кастомных Gradle Templates, при резолве зависимостей ExternalDependencyManager патчит эти темплейты, и дешугаринг идет стандартным путем.

Мы работаем над решением этой проблемы, однако самым простым и быстрым решением на данный момент видится использование кастомных Gradle Template'ов.

В качестве альтернативы вы можете попробовать установить значение `android.enableDexingArtifactTransform=false` в файле `UnityInstallationDirectory/PlaybackEngines/AndroidPlayer/Tools/GradleTemplates/gradleTemplate.properties`.

**Comment by Sergey1296** [comment]
@mobile-ads-github Здравствуйте. Я уже решил проблему на версии 6.1.0 подключив Custom Gradle. Все работает спасибо
