### ISSUE TITLE
Не устанавливается release-6.3.0 на чистый проект

### ISSUE THREAD

**Issue by RendezvousGames** [yandexmobile/yandex-ads-unity-plugin#87]
Никак не могу установить из коробки. Виснит на 100%. Пробовал разные версии юнити
![photo_2024-01-06_16-30-12](https://github.com/yandexmobile/yandex-ads-unity-plugin/assets/145895222/7bffe34d-a2fc-4bb5-9f93-e94f423b8b50)

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-2785. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-2785 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by mobile-ads-github** [comment]
![unity-custom](https://github.com/yandexmobile/yandex-ads-unity-plugin/assets/31896236/c1f7bd52-f0dd-4604-a1f6-2a3eccfba129)
Добрый день! Необходимо включить настройку **Custom Main Gradle Template** и **Custom Gradle Properties Template**.
