### ISSUE TITLE
Реклама занимает главный поток Unity

### ISSUE THREAD

**Issue by anomal3** [yandexmobile/yandex-ads-unity-plugin#88]
Доброго дня. Как быть когда игра мультиплеерная и занимать главный поток не представляется возможным? Можно ли показ рекламы вызвать внутри контрола а не поверх приложения через aar? или может вызывать асинхронный показ видео?

Есть ли какие способы?

Использование **UnityMainThreadDispatcher**  не принёс результатов

```csharp
//Вызвав показ так не даёт результат
UnityMainThreadDispatcher.Instance().Enqueue(() => rewarded.Show());
```

**Comment by mobile-ads-github** [comment]
Добрый день! Приносим извинение за долгий ответ. К сожалению, на данный момент невозможно обойтись без использования MainThread из-за технических ограничений. Запрос за рекламой должен быть из главного потока.
