### ISSUE TITLE
Во время показа рекламы Interstitial и Rewarded прозрачное пространство

### ISSUE THREAD

**Issue by RocksteadyDog** [yandexmobile/yandex-ads-unity-plugin#91]
Здравствуйте!

Во время показа рекламы Interstitial и Rewarded прозрачное пространство где вставка safearea, где на телефоне камера, я прикрепил скриншоты, тестировал на pixel 6. Сделайте фон под размер всего экрана и цветом фона рекламы и уж точно не прозрачным, проблема хорошо видна на первом скриншоте, как пример скриншот рекламы unity, где свободное пространство залито черным.

<details>
<summary>Скриншоты</summary>

![1](https://github.com/yandexmobile/yandex-ads-unity-plugin/assets/29661837/23e58ce6-eacc-41e9-97cd-22cd81d5721d)
![2](https://github.com/yandexmobile/yandex-ads-unity-plugin/assets/29661837/660e3d0b-63e1-4069-9458-28fd9e426c91)
![unity](https://github.com/yandexmobile/yandex-ads-unity-plugin/assets/29661837/43f87207-fabd-4a27-8bc5-009725bd198e)
</details>

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-2840. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-2840 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.
