### ISSUE TITLE
Версия 6.3.0 несовместима с AdMob 8.7.0

### ISSUE THREAD

**Issue by hippogamesunity** [yandexmobile/yandex-ads-unity-plugin#92]
Создать новый проект в Unity 2022 LTS, импортировать последнюю версию AdMob, собрать - все ок.
Импортировать последнюю версию YandesAds 6.3.0, собрать - не собирается.

Execution failed for task ':unityLibrary:mergeReleaseJavaResource'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeJavaResWorkAction
   > 2 files found with path 'META-INF/kotlinx-serialization-json.kotlin_module' from inputs:
      - D:\GitHub\PixelDiffusion\Library\Bee\Android\Prj\IL2CPP\Gradle\unityLibrary\libs\org.jetbrains.kotlinx.kotlinx-serialization-json-1.3.2.jar
      - D:\GitHub\PixelDiffusion\Library\Bee\Android\Prj\IL2CPP\Gradle\unityLibrary\libs\org.jetbrains.kotlinx.kotlinx-serialization-json-jvm-1.3.2.jar

Откатился обратно на версию 6.0.1 - все собирается.

**Comment by hippogamesunity** [comment]
Версия 6.3.0

**Comment by hippogamesunity** [comment]
Версия 7.0.0 - та же ошибка в чистом проекте на Unity 2021.3.36+

**Comment by mobile-ads-github** [comment]
Здравствуйте!  С версией 7.0.0 должен работать Google Mobile Ads Unity Plugin  версии 9.0 в составе которого:
- Google Mobile Ads Android SDK 23.0.0
- Google Mobile Ads iOS SDK 11.2.0
