### ISSUE TITLE
Поддержка IronSourceSDK 7.7.0

### ISSUE THREAD

**Issue by anton-shelestov** [yandexmobile/yandex-ads-unity-plugin#93]
При попытке собрать iOS билд юнити проекта с подключенной IronSource SDK 7.7.0 и YandexAdsISAdapter произойдет ошибка
`pod install --repo-update
Updating local specs repositories
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "IronSourceSDK":
  In Podfile:
    IronSourceSDK (= 7.7.0.0)

    IronSourceYandexMobileAdsAdapters (= 7.6.0.0) was resolved to 7.6.0.0, which depends on
      IronSourceSDK (~> 7.6.0.0)

Specs satisfying the `IronSourceSDK (= 7.7.0.0), IronSourceSDK (~> 7.6.0.0)` dependency were found, but they required a higher minimum deployment target.`

Добавьте, пожалуйста, поддержку IronSource SDK 7.7.0

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-2900. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-2900 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.
